<?php
declare(strict_types=1);


return static function (\PDO $pdo, array $m): void {
    $json = static fn(mixed $v): string => json_encode($v ?? [], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    $now = gmdate('Y-m-d H:i:s');

    $control = $pdo->prepare('INSERT INTO story_controls (stable_key,position,family_key,family_label,title,short_title,description,control_type,default_value,enabled,affected_quadrants_json,tags_json,narrative_axes_json,conflicts_json,synergies_json,metadata_json,manifest_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE position=VALUES(position), family_key=VALUES(family_key), family_label=VALUES(family_label), title=VALUES(title), short_title=VALUES(short_title), description=VALUES(description), control_type=VALUES(control_type), default_value=VALUES(default_value), enabled=VALUES(enabled), affected_quadrants_json=VALUES(affected_quadrants_json), tags_json=VALUES(tags_json), narrative_axes_json=VALUES(narrative_axes_json), conflicts_json=VALUES(conflicts_json), synergies_json=VALUES(synergies_json), manifest_version=VALUES(manifest_version), updated_at=VALUES(updated_at)');
    foreach ($m['story-controls']['items'] as $i) { $control->execute([$i['id'],$i['position'],$i['familyId'],$i['familyLabel'],$i['title'],$i['shortTitle'],$i['description'],$i['controlType'],(int)$i['defaultValue'],(int)$i['enabled'],$json($i['affectedQuadrants']),$json($i['tags']),$json($i['narrativeAxes']),$json($i['conflicts']),$json($i['synergies']),$json($i['metadata']),$m['story-controls']['manifestVersion'],$now,$now]); }

    $widget = $pdo->prepare('INSERT INTO story_widgets (stable_key,position,title,short_title,description,activation_button_id,panel_id,exclusive_panel,parameters_json,affected_quadrants_json,narrative_axes_json,future_capabilities_json,metadata_json,enabled,manifest_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE position=VALUES(position), title=VALUES(title), short_title=VALUES(short_title), description=VALUES(description), activation_button_id=VALUES(activation_button_id), panel_id=VALUES(panel_id), exclusive_panel=VALUES(exclusive_panel), parameters_json=VALUES(parameters_json), affected_quadrants_json=VALUES(affected_quadrants_json), narrative_axes_json=VALUES(narrative_axes_json), future_capabilities_json=VALUES(future_capabilities_json), enabled=VALUES(enabled), manifest_version=VALUES(manifest_version), updated_at=VALUES(updated_at)');
    foreach ($m['story-widgets']['items'] as $i) { $widget->execute([$i['id'],$i['position'],$i['title'],$i['shortTitle'],$i['description'],$i['activationButtonId'],$i['panelId'],(int)$i['exclusivePanel'],$json($i['parameters']),$json($i['affectedQuadrants']),$json($i['narrativeAxes']),$json($i['futureCapabilities']),$json($i['metadata']),(int)$i['enabled'],$m['story-widgets']['manifestVersion'],$now,$now]); }

    $version = $pdo->prepare('INSERT INTO story_versions (stable_key,version_number,position,title,short_title,description,temporal_profile_json,world_profile_json,machine_profile_json,kitchen_profile_json,threat_profile_json,emotional_profile_json,residue_profile_json,title_patterns_json,abuela_line_themes_json,required_tags_json,preferred_tags_json,excluded_tags_json,default_widget_configuration_json,metadata_json,enabled,manifest_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE version_number=VALUES(version_number), position=VALUES(position), title=VALUES(title), short_title=VALUES(short_title), description=VALUES(description), temporal_profile_json=VALUES(temporal_profile_json), world_profile_json=VALUES(world_profile_json), machine_profile_json=VALUES(machine_profile_json), kitchen_profile_json=VALUES(kitchen_profile_json), threat_profile_json=VALUES(threat_profile_json), emotional_profile_json=VALUES(emotional_profile_json), residue_profile_json=VALUES(residue_profile_json), title_patterns_json=VALUES(title_patterns_json), abuela_line_themes_json=VALUES(abuela_line_themes_json), required_tags_json=VALUES(required_tags_json), preferred_tags_json=VALUES(preferred_tags_json), excluded_tags_json=VALUES(excluded_tags_json), default_widget_configuration_json=VALUES(default_widget_configuration_json), enabled=VALUES(enabled), manifest_version=VALUES(manifest_version), updated_at=VALUES(updated_at)');
    foreach ($m['story-versions']['items'] as $i) { $version->execute([$i['id'],$i['versionNumber'],$i['position'],$i['title'],$i['shortTitle'],$i['description'],$json($i['temporalProfile']),$json($i['worldProfile']),$json($i['machineProfile']),$json($i['kitchenProfile']),$json($i['threatProfile']),$json($i['emotionalProfile']),$json($i['residueProfile']),$json($i['titlePatterns']),$json($i['abuelaLineThemes']),$json($i['requiredTags']),$json($i['preferredTags']),$json($i['excludedTags']),$json($i['defaultWidgetConfiguration']),$json($i['metadata']),(int)$i['enabled'],$m['story-versions']['manifestVersion'],$now,$now]); }

    $quadrant = $pdo->prepare('INSERT INTO quadrants (stable_key,number,position,block_key,block_label,fixed_function,narrative_purpose,aspect_class,grid_area,continuity_group,narrative_weight,previous_quadrant_key,next_quadrant_key,gutter_before_key,gutter_after_key,affected_controls_json,affected_widgets_json,allowed_version_ids_json,image_required,caption_allowed,dialogue_allowed,metadata_json,manifest_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE number=VALUES(number), position=VALUES(position), block_key=VALUES(block_key), block_label=VALUES(block_label), fixed_function=VALUES(fixed_function), narrative_purpose=VALUES(narrative_purpose), aspect_class=VALUES(aspect_class), grid_area=VALUES(grid_area), continuity_group=VALUES(continuity_group), narrative_weight=VALUES(narrative_weight), previous_quadrant_key=VALUES(previous_quadrant_key), next_quadrant_key=VALUES(next_quadrant_key), gutter_before_key=VALUES(gutter_before_key), gutter_after_key=VALUES(gutter_after_key), affected_controls_json=VALUES(affected_controls_json), affected_widgets_json=VALUES(affected_widgets_json), allowed_version_ids_json=VALUES(allowed_version_ids_json), image_required=VALUES(image_required), caption_allowed=VALUES(caption_allowed), dialogue_allowed=VALUES(dialogue_allowed), manifest_version=VALUES(manifest_version), updated_at=VALUES(updated_at)');
    foreach ($m['quadrants']['items'] as $i) { $quadrant->execute([$i['stableKey'],$i['number'],$i['position'],$i['blockId'],$i['blockLabel'],$i['fixedFunction'],$i['narrativePurpose'],$i['aspectClass'],$i['gridArea'],$i['continuityGroup'],$i['narrativeWeight'],$i['previousQuadrant'] ?: null,$i['nextQuadrant'] ?: null,$i['gutterBefore'] ?: null,$i['gutterAfter'] ?: null,$json($i['affectedByControls']),$json($i['affectedByWidgets']),$json($i['allowedVersionIds']),(int)$i['imageRequired'],(int)$i['captionAllowed'],(int)$i['dialogueAllowed'],$json($i['metadata']),$m['quadrants']['manifestVersion'],$now,$now]); }

    $qId = $vId = [];
    foreach ($pdo->query('SELECT id, stable_key FROM quadrants') as $r) { $qId[$r['stable_key']] = $r['id']; }
    foreach ($pdo->query('SELECT id, stable_key FROM story_versions') as $r) { $vId[$r['stable_key']] = $r['id']; }
    $variant = $pdo->prepare("INSERT INTO quadrant_variants (slot_key,quadrant_id,story_version_id,quadrant_number,version_number,position,title,description,narrative_payload_json,tags_json,required_controls_json,excluded_controls_json,widget_constraints_json,status,revision,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE quadrant_id=VALUES(quadrant_id), story_version_id=VALUES(story_version_id), quadrant_number=VALUES(quadrant_number), version_number=VALUES(version_number), position=VALUES(position), title=VALUES(title), description=VALUES(description), narrative_payload_json=VALUES(narrative_payload_json), tags_json=VALUES(tags_json), required_controls_json=VALUES(required_controls_json), excluded_controls_json=VALUES(excluded_controls_json), widget_constraints_json=VALUES(widget_constraints_json), status=IF(FIELD(status,'empty','planned','draft','review','approved','published') > 0 AND FIELD(status,'empty','planned','draft','review','approved','published') < FIELD(VALUES(status),'empty','planned','draft','review','approved','published'), VALUES(status), status), updated_at=VALUES(updated_at)");
    $asset = $pdo->prepare("INSERT INTO media_assets (quadrant_variant_id,asset_path,expected_path,mime_type,width,height,aspect_ratio,alt_text,caption,status,checksum,revision,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE expected_path=VALUES(expected_path), alt_text=VALUES(alt_text), asset_path=COALESCE(asset_path,VALUES(asset_path)), mime_type=COALESCE(mime_type,VALUES(mime_type)), width=COALESCE(width,VALUES(width)), height=COALESCE(height,VALUES(height)), aspect_ratio=COALESCE(aspect_ratio,VALUES(aspect_ratio)), caption=COALESCE(caption,VALUES(caption)), checksum=COALESCE(checksum,VALUES(checksum)), status=IF(FIELD(status,'empty','planned','draft','review','approved','published') > 0 AND FIELD(status,'empty','planned','draft','review','approved','published') < FIELD(VALUES(status),'empty','planned','draft','review','approved','published'), VALUES(status), status), updated_at=VALUES(updated_at)");
    $selectVariant = $pdo->prepare('SELECT id FROM quadrant_variants WHERE slot_key=?');
    foreach ($m['quadrant-slots']['items'] as $i) { $variant->execute([$i['id'],$qId[$i['quadrantId']],$vId[$i['versionId']],$i['quadrantNumber'],$i['versionNumber'],$i['position'],$i['id'],'Slot narrativo canônico '.$i['id'],$json([]),$json([]),$json([]),$json([]),$json([]),$i['status'],max(1,(int)$i['revision']),$json($i['metadata']),$now,$now]); $selectVariant->execute([$i['id']]); $variantId=(int)$selectVariant->fetchColumn(); $d=$i['dimensions']; $asset->execute([$variantId,$i['asset']['path'] ?: null,$i['asset']['expectedPath'],$i['asset']['mimeType'] ?: null,$d['width'] ?: null,$d['height'] ?: null,$d['aspectRatio'] ?: null,$i['altText'],$i['caption'] ?: null,$i['status'],$i['checksum'] ?: null,max(1,(int)$i['revision']),$json($i['metadata']),$now,$now]); }
};
