import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
const controls = JSON.parse(fs.readFileSync(new URL('../../../data/story-controls.json', import.meta.url), 'utf8')).items;
const dashboardDemoSource = fs.readFileSync(new URL('../../../data/dashboard-hub-demo.js', import.meta.url), 'utf8');
const dashboardSource = fs.readFileSync(new URL('../../../scripts/dashboard-hub.js', import.meta.url), 'utf8');
const bridgeSource = fs.readFileSync(new URL('../src/app/core/dashboard-bridge.service.ts', import.meta.url), 'utf8');
const persistenceSource = fs.readFileSync(new URL('../src/app/core/story-persistence.service.ts', import.meta.url), 'utf8');
const demoIds = ['arquivo','pesquisa','comunidade','oficina','historia','colecao','sistemas','laboratorio'];

test('dashboard grid is sourced from story-controls manifest and remains exactly 32 controls', () => { assert.equal(controls.length, 32); assert.match(dashboardSource, /import storyControlsManifest from '..\/data\/story-controls\.json' with \{ type: 'json' \}/); assert.match(dashboardSource, /const canonicalControlItems = \(storyControlsManifest\.items \|\| \[\]\)\.slice\(\)\.sort\(\(a,b\)=>a\.position-b\.position\)/); assert.match(dashboardSource, /const items=canonicalControlItems\.map\(\(control\)=>/); });
test('all emitted and persisted control ids are canonical, never demonstrative ids', () => { const ids = new Set(controls.map(control => control.id)); for (const id of ids) assert.equal(demoIds.includes(id), false); for (const id of demoIds) assert.match(dashboardDemoSource.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''), new RegExp(id)); assert.match(dashboardSource, /const publicControlsState = \(\) => Object\.fromEntries\(canonicalControlItems\.map\(\(item\)=>\[item\.id,Boolean\(dashboardState\.features\[item\.id\]\?\.enabled\)\]\)\)/); assert.match(dashboardSource, /const FEATURE_STORAGE_KEY = 'dashboard-hub:v3:feature-state'/); assert.match(dashboardSource, /filter\(\(\[id,value\]\)=>canonicalControlIds\.has\(id\)&&typeof value==='boolean'\)/); });
test('button click emits dashboard:feature-toggle and bridge queues only accepted canonical controls', () => { assert.match(dashboardSource, /'data-feature-id':item\.id/); assert.match(dashboardSource, /emit\('dashboard:feature-toggle',\{ featureId, enabled:Boolean\(enabled\) \}\)/); assert.match(bridgeSource, /INVALID_CONTROL_ID/); assert.match(bridgeSource, /this\.persistence\.queueControls\(\{\[String\(d\['featureId'\]\)\]:Boolean\(d\['enabled'\]\)\}\)/); assert.match(persistenceSource, /queueControls\(controls:Record<string,boolean>\)/); });
test('restore and snapshot contract use the same data-feature-id buttons and exactly 32 booleans', () => { assert.match(dashboardSource, /function getFeatureButtonById\(root, featureId\)\{ return root\.querySelector\(`\[data-feature-toggle\]\[data-feature-id="\$\{CSS\.escape\(featureId\)\}"\]`\); \}/); assert.match(dashboardSource, /Object\.entries\(state\?\.controls\|\|\{\}\)\.forEach/); assert.match(bridgeSource, /Object\.keys\(cc\)\.length!==32/); const snapshot = Object.fromEntries(controls.map(item => [item.id, Boolean(item.defaultValue)])); assert.equal(Object.keys(snapshot).length, 32); assert.equal(Object.values(snapshot).every(value => typeof value === 'boolean'), true); });
