import {computed,Injectable,signal} from '@angular/core';import {BootstrapManifests,QuadrantSlot,StoryEngineError,StoryEngineState} from '../story-engine.models';
const empty={controls:[],widgets:[],versions:[],quadrants:[],slots:[]};
@Injectable({providedIn:'root'}) export class StoryStateService{private readonly s=signal<StoryEngineState>({status:'idle',activeVersionId:'v01',manifests:empty,activeSelections:{},errors:[],initializedAt:null,revision:0});readonly state=this.s.asReadonly();readonly quadrants=computed(()=>this.s().manifests.quadrants);readonly selections=computed(()=>this.s().activeSelections);readonly ready=computed(()=>this.s().status==='ready');readonly quadrantsById=computed(()=>new Map(this.s().manifests.quadrants.map(q=>[q.id,q])));readonly versionsById = computed(
  () =>
    new Map<string, StoryVersion>(
      this.s().manifests.versions.map(version => [
        version.id,
        version,
      ])
    )
);readonly slotsByCompositeKey=computed(()=>new Map(this.s().manifests.slots.map(sl=>[`${sl.quadrantId}:${sl.versionId}`,sl])));setLoading(defaultVersionId:string){this.s.update(v=>({...v,status:'loading',activeVersionId:defaultVersionId,errors:[]}))}setReady(m:BootstrapManifests,defaultVersionId:string){const sel=Object.fromEntries(m.quadrants.map(q=>[q.id,defaultVersionId]));this.s.set({status:'ready',activeVersionId:defaultVersionId,manifests:m,activeSelections:sel,errors:[],initializedAt:Date.now(),revision:0})}setError(e:StoryEngineError){this.s.update(v=>({...v,status:'error',errors:[...v.errors,e]}))}activeSlot(qid:string):QuadrantSlot|undefined{return this.slotsByCompositeKey().get(`${qid}:${this.s().activeSelections[qid]}`)}setQuadrantVersion(qid:string,vid:string){const st=this.s();if(st.status!=='ready')return{success:false,error:{code:'ENGINE_NOT_READY'}};if(!this.quadrantsById().has(qid))return{success:false,error:{code:'QUADRANT_NOT_FOUND'}};if(!this.versionsById().has(vid))return{success:false,error:{code:'VERSION_NOT_FOUND'}};const slot=this.slotsByCompositeKey().get(`${qid}:${vid}`);if(!slot)return{success:false,error:{code:'SLOT_NOT_FOUND'}};const revision=st.revision+1;this.s.update(v=>({...v,activeSelections:{...v.activeSelections,[qid]:vid},revision}));return{success:true,quadrantId:qid,versionId:vid,slotId:slot.id,revision}}setAll(versionId:string){return{success:this.s().manifests.quadrants.map(q=>this.setQuadrantVersion(q.id,versionId)).every(r=>r.success)}}reset(){return this.setAll(this.s().activeVersionId)}snapshot(){return JSON.parse(JSON.stringify(this.s())) as StoryEngineState}}
