<?php
declare(strict_types=1);

namespace Tna\Story;

use PDO;
use RuntimeException;

final class WeightedNarrativeResolver implements StoryResolverInterface
{
    public const RESOLUTION_MODE = 'weighted-participatory-v1';
    private BaselineStoryResolver $fallback;
    public function __construct(private readonly string $rulesPath = __DIR__ . '/../../../data/story-resolution-rules.json', ?BaselineStoryResolver $fallback = null){$this->fallback=$fallback??new BaselineStoryResolver();}
    public function resolve(PDO $pdo, int $seed, array $controls = [], array $widgets = [], int $revision = 1): array
    { try { return $this->resolveWeighted($pdo,$seed,$controls,$widgets,$revision); } catch (\Throwable $e) { $r=$this->fallback->resolve($pdo,$seed,$controls,$widgets,$revision); $r['trace']['fallbackUsed']=true; $r['trace']['fallbackReason']=$e->getMessage(); $r['resolvedState']['resolutionMode']='baseline-fallback-v1'; return $r; } }
    private function resolveWeighted(PDO $pdo,int $seed,array $controls,array $widgets,int $revision): array
    {
        if(!is_file($this->rulesPath)){throw new RuntimeException('Rules manifest is absent.');}
        $rules=json_decode((string)file_get_contents($this->rulesPath),true); if(!is_array($rules)||empty($rules['rulesVersion'])){throw new RuntimeException('Rules manifest is invalid.');}
        $versions=$this->versions($pdo); $variantCount=(int)$pdo->query('SELECT COUNT(*) FROM quadrant_variants')->fetchColumn(); $variants=$this->variants($pdo); if(count($versions)!==7){throw new RuntimeException('Catalog must contain seven enabled story versions.');} if($variantCount!==203){throw new RuntimeException('Catalog must contain exactly 203 quadrant variants.');}
        $knownControls=$this->controlKeys($pdo); $state=$this->normalizeState($controls,$widgets,$knownControls); $stateHash=hash('sha256',json_encode([$seed,$state,$revision,$rules['rulesVersion']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
        $scores=array_fill_keys(array_keys($versions),0.0); $controlInfluences=[]; $axisTotals=[];
        foreach($state['controls'] as $id=>$on){ if(!$on)continue; $aff=$rules['controlAffinities'][$id]['axes']??null; if(!is_array($aff)){ $controlInfluences[$id]=['ignored'=>true,'reason'=>'missing-rule']; continue; } $delta=$this->scoreAxes($scores,$aff,$rules,$axisTotals); $controlInfluences[$id]=['enabled'=>true,'axes'=>$aff,'versionDelta'=>$delta]; }
        $widgetInfluences=$this->applyWidgets($scores,$state['widgets'],$rules,$axisTotals);
        $this->applyRelations($scores,$rules,$axisTotals);
        $dominant=$this->pick($scores,$seed,$stateHash,'global'); $title=$versions[$dominant]['title'];
        $blocks=[]; foreach($this->blocks($variants) as $bk=>$b){$bs=$scores; foreach(($rules['blockAffinities'][$bk]??[]) as $axis=>$w){foreach($versions as $vid=>$_){$bs[$vid]+=(float)($rules['profiles'][$vid][$axis]??0)*$w;}} $blocks[$bk]=['info'=>$b,'scores'=>$bs];}
        $selected=[]; $continuity=[]; $prev=null; $allowMix=$this->mixingAllowed($axisTotals,$rules); $maxSecondary=$allowMix?($rules['variationLimits']['expandedSecondaryVersions']??4):($rules['variationLimits']['defaultSecondaryVersions']??2);
        foreach($blocks as $bk=>$b){$bs=$b['scores']; if($prev){$bs[$prev]+= (float)$rules['continuityRules']['sameVersionBonus']; $continuity[]=['block'=>$bk,'previousVersion'=>$prev,'bonus'=>$rules['continuityRules']['sameVersionBonus']];} $bs[$dominant]+=(float)$rules['continuityRules']['dominantBonus']; $chosen=$this->pick($bs,$seed,$stateHash,$bk); $selected[$bk]=$chosen; $prev=$chosen;}
        $selected['activation']=$dominant; // q07/title block reflects dominant.
        if($allowMix){ foreach(['world','consequences'] as $mixBlock){ if(isset($blocks[$mixBlock])){ $rank=$blocks[$mixBlock]['scores']; arsort($rank); foreach(array_keys($rank) as $candidate){ if($candidate!==$dominant){ $selected[$mixBlock]=$candidate; break; } } } } }
        if($allowMix && isset($selected['world'])){ $selected['crisis']=$selected['world']; }
        $used=array_values(array_unique($selected)); $second=array_values(array_diff($used,[$dominant])); if(count($second)>$maxSecondary){$keep=array_slice($second,0,(int)$maxSecondary); foreach($selected as $bk=>$v){if($v!==$dominant&&!in_array($v,$keep,true))$selected[$bk]=$dominant;}}
        $sels=[]; $blockOut=[]; foreach($variants as $q=>$byV){$bk=$byV['__q']['block_key']; $vid=$selected[$bk]??$dominant; if(!isset($byV[$vid])){throw new RuntimeException("Missing slot for $q/$vid");} $row=$byV[$vid]; $sels[]=['position'=>(int)$row['position'],'quadrant'=>['id'=>$row['quadrant_key'],'number'=>(int)$row['quadrant_number'],'blockId'=>$row['block_key'],'blockLabel'=>$row['block_label']],'slotId'=>$row['slot_key'],'version'=>$vid,'title'=>$row['title'],'selectionReason'=>'weighted block '.$row['block_key'].' selected '.$vid,'payload'=>json_decode((string)$row['narrative_payload_json'],true)?:[],'_ids'=>['quadrantId'=>(int)$row['quadrant_id'],'variantId'=>(int)$row['variant_id']]]; $blockOut[$bk]=['id'=>$bk,'label'=>$row['block_label'],'version'=>$vid];}
        if(count($sels)!==29){throw new RuntimeException('Resolver did not produce 29 selections.');}
        return ['title'=>$title,'resolutionMode'=>self::RESOLUTION_MODE,'dominantVersion'=>$dominant,'dominantVersionId'=>(int)$versions[$dominant]['id'],'seed'=>$seed,'versions'=>['dominant'=>$dominant,'blocks'=>array_values($blockOut)],'blocks'=>array_values($blockOut),'selections'=>$sels,'resolvedState'=>['title'=>$title,'resolutionMode'=>self::RESOLUTION_MODE,'dominantVersion'=>$dominant,'secondaryVersions'=>array_values(array_diff(array_unique(array_column($sels,'version')),[$dominant])),'selectionCount'=>29,'blockCount'=>count($blockOut),'rulesVersion'=>$rules['rulesVersion'],'stateHash'=>$stateHash],'trace'=>['resolver'=>'WeightedNarrativeResolver','rulesVersion'=>$rules['rulesVersion'],'seed'=>$seed,'stateHash'=>$stateHash,'weightsApplied'=>true,'globalVersionScores'=>$scores,'selectedDominantVersion'=>$dominant,'blockSelections'=>$selected,'activeControlInfluences'=>$controlInfluences,'widgetInfluences'=>$widgetInfluences,'continuityAdjustments'=>$continuity,'tieBreaks'=>[],'fallbackUsed'=>false,'fallbackReason'=>null]];
    }
    private function scoreAxes(array &$scores,array $axes,array $rules,array &$axisTotals): array { $d=[]; foreach($axes as $axis=>$w){ if(str_starts_with((string)$axis,'v')){$scores[$axis]+=(float)$w; $d[$axis]=($d[$axis]??0)+$w; continue;} $axisTotals[$axis]=($axisTotals[$axis]??0)+(float)$w; foreach($scores as $v=>$_){$add=(float)($rules['profiles'][$v][$axis]??0)*(float)$w; $scores[$v]+=$add; $d[$v]=($d[$v]??0)+$add;}} return $d; }
    private function applyWidgets(array &$scores,array $widgets,array $rules,array &$axisTotals): array { $out=[]; $map=['past'=>['past'=>2],'present'=>['present'=>2],'future'=>['future'=>2],'mixed'=>['paradox'=>1.6],'deep-prehistory'=>['past'=>1.5],'ancestral'=>['ancestry'=>1.5],'historical'=>['ancestry'=>1,'past'=>.7],'expanded-present'=>['present'=>1.5],'distant-future'=>['future'=>1.5],'backward'=>['past'=>1],'forward'=>['future'=>1],'circular'=>['paradox'=>1.2],'tapioca'=>['v01'=>1.3,'kitchen'=>.5],'corn-cake'=>['v02'=>1,'v03'=>.5],'clay-pot'=>['v05'=>1,'ancestry'=>.7],'unstable'=>['rupture'=>1.2,'paradox'=>.8]]; foreach($widgets as $wid=>$params){ if(!is_array($params))continue; foreach($params as $k=>$v){$axes=[]; if(is_numeric($v)){ $n=max(0,min(100,(float)$v))/100; if(in_array($k,['paradox-level','rupture-probability','error-rate'],true))$axes=['paradox'=>2*$n,'rupture'=>$n]; elseif($k==='melancholy')$axes=['melancholy'=>2*$n]; elseif($k==='danger')$axes=['danger'=>2*$n]; elseif($k==='humor')$axes=['humor'=>2*$n]; elseif($k==='wonder')$axes=['wonder'=>2*$n]; elseif($k==='imagination-reality-balance')$axes=$n>=.5?['imagination'=>2*$n]:['reality'=>2*(1-$n)]; elseif(str_contains($k,'coherence')||$k==='stability')$axes=['reality'=>2*$n,'machine'=>$n]; elseif(str_contains($k,'matrix')||str_contains($k,'memory'))$axes=['ancestry'=>$n,'kitchen'=>$n]; }
                elseif(is_string($v)){$axes=$map[$v]??[];} if($axes){$out[$wid][$k]=['value'=>$v,'axes'=>$axes,'versionDelta'=>$this->scoreAxes($scores,$axes,$rules,$axisTotals)];}}} return $out; }
    private function applyRelations(array &$scores,array $rules,array $axisTotals): void { foreach($rules['synergyRules']??[] as $r){ if(min(array_map(fn($a)=>$axisTotals[$a]??0,$r['axes']))>0){foreach($scores as $v=>$_)$scores[$v]+=(float)($r['bonus']??0)*array_sum(array_intersect_key($rules['profiles'][$v],array_flip($r['axes'])));}} }
    private function pick(array $scores,int $seed,string $hash,string $ctx): string { uksort($scores,fn($a,$b)=>($scores[$b]<=>$scores[$a]) ?: strcmp(hash('sha256',$hash.$seed.$ctx.$a),hash('sha256',$hash.$seed.$ctx.$b))); return array_key_first($scores); }
    private function mixingAllowed(array $axisTotals,array $rules): bool { foreach($rules['variationLimits']['mixingAxes']??[] as $a){if(($axisTotals[$a]??0)>=(float)$rules['variationLimits']['mixingThreshold'])return true;} return false; }
    private function normalizeState(array $controls,array $widgets,array $known): array { ksort($controls); ksort($widgets); return ['controls'=>array_intersect_key(array_map('boolval',$controls),array_flip($known)),'widgets'=>$widgets]; }
    private function versions(PDO $pdo): array { $r=[]; foreach($pdo->query('SELECT id,stable_key,title FROM story_versions WHERE enabled=1 ORDER BY stable_key') as $row){$r[$row['stable_key']]=$row;} return $r; }
    private function controlKeys(PDO $pdo): array { return $pdo->query('SELECT stable_key FROM story_controls WHERE enabled=1')->fetchAll(PDO::FETCH_COLUMN)?:[]; }
    private function variants(PDO $pdo): array { $sql="SELECT qv.id variant_id,qv.slot_key,qv.quadrant_id,qv.quadrant_number,qv.position,qv.title,qv.narrative_payload_json,sv.stable_key version_key,q.stable_key quadrant_key,q.block_key,q.block_label FROM quadrant_variants qv JOIN story_versions sv ON sv.id=qv.story_version_id JOIN quadrants q ON q.id=qv.quadrant_id WHERE sv.enabled=1 ORDER BY qv.quadrant_number, sv.stable_key"; $o=[]; foreach($pdo->query($sql) as $r){$q=$r['quadrant_key']; $o[$q]['__q']=$r; $o[$q][$r['version_key']]=$r;} return $o; }
    private function blocks(array $variants): array { $b=[]; foreach($variants as $q=>$v){$r=$v['__q']; $b[$r['block_key']]=['id'=>$r['block_key'],'label'=>$r['block_label']];} return $b; }
}
