CREATE TABLE story_controls (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    stable_key VARCHAR(100) NOT NULL,
    position INT UNSIGNED NOT NULL,
    family_key VARCHAR(100) NOT NULL,
    family_label VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    short_title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    control_type VARCHAR(50) NOT NULL,
    default_value TINYINT(1) NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    affected_quadrants_json LONGTEXT NOT NULL,
    tags_json LONGTEXT NOT NULL,
    narrative_axes_json LONGTEXT NOT NULL,
    conflicts_json LONGTEXT NOT NULL,
    synergies_json LONGTEXT NOT NULL,
    metadata_json LONGTEXT NOT NULL,
    manifest_version VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_story_controls_stable_key (stable_key),
    UNIQUE KEY uq_story_controls_position (position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE story_widgets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    stable_key VARCHAR(100) NOT NULL,
    position INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    short_title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    activation_button_id VARCHAR(100) NOT NULL,
    panel_id VARCHAR(100) NOT NULL,
    exclusive_panel TINYINT(1) NOT NULL DEFAULT 0,
    parameters_json LONGTEXT NOT NULL,
    affected_quadrants_json LONGTEXT NOT NULL,
    narrative_axes_json LONGTEXT NOT NULL,
    future_capabilities_json LONGTEXT NOT NULL,
    metadata_json LONGTEXT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    manifest_version VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_story_widgets_stable_key (stable_key),
    UNIQUE KEY uq_story_widgets_position (position),
    UNIQUE KEY uq_story_widgets_panel_id (panel_id),
    UNIQUE KEY uq_story_widgets_activation_button_id (activation_button_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE story_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    stable_key VARCHAR(100) NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    short_title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    temporal_profile_json LONGTEXT NOT NULL,
    world_profile_json LONGTEXT NOT NULL,
    machine_profile_json LONGTEXT NOT NULL,
    kitchen_profile_json LONGTEXT NOT NULL,
    threat_profile_json LONGTEXT NOT NULL,
    emotional_profile_json LONGTEXT NOT NULL,
    residue_profile_json LONGTEXT NOT NULL,
    title_patterns_json LONGTEXT NOT NULL,
    abuela_line_themes_json LONGTEXT NOT NULL,
    required_tags_json LONGTEXT NOT NULL,
    preferred_tags_json LONGTEXT NOT NULL,
    excluded_tags_json LONGTEXT NOT NULL,
    default_widget_configuration_json LONGTEXT NOT NULL,
    metadata_json LONGTEXT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    manifest_version VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_story_versions_stable_key (stable_key),
    UNIQUE KEY uq_story_versions_version_number (version_number),
    UNIQUE KEY uq_story_versions_position (position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quadrants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    stable_key VARCHAR(100) NOT NULL,
    number INT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL,
    block_key VARCHAR(100) NOT NULL,
    block_label VARCHAR(255) NOT NULL,
    fixed_function VARCHAR(255) NOT NULL,
    narrative_purpose TEXT NOT NULL,
    aspect_class VARCHAR(100) NOT NULL,
    grid_area VARCHAR(100) NOT NULL,
    continuity_group VARCHAR(100) NOT NULL,
    narrative_weight DECIMAL(6,3) NOT NULL DEFAULT 1.000,
    previous_quadrant_key VARCHAR(100) NULL,
    next_quadrant_key VARCHAR(100) NULL,
    gutter_before_key VARCHAR(100) NULL,
    gutter_after_key VARCHAR(100) NULL,
    affected_controls_json LONGTEXT NOT NULL,
    affected_widgets_json LONGTEXT NOT NULL,
    allowed_version_ids_json LONGTEXT NOT NULL,
    image_required TINYINT(1) NOT NULL DEFAULT 1,
    caption_allowed TINYINT(1) NOT NULL DEFAULT 1,
    dialogue_allowed TINYINT(1) NOT NULL DEFAULT 1,
    metadata_json LONGTEXT NOT NULL,
    manifest_version VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_quadrants_stable_key (stable_key),
    UNIQUE KEY uq_quadrants_number (number),
    UNIQUE KEY uq_quadrants_position (position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quadrant_variants (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    slot_key VARCHAR(100) NOT NULL,
    quadrant_id BIGINT UNSIGNED NOT NULL,
    story_version_id BIGINT UNSIGNED NOT NULL,
    quadrant_number INT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    narrative_payload_json LONGTEXT NOT NULL,
    tags_json LONGTEXT NOT NULL,
    required_controls_json LONGTEXT NOT NULL,
    excluded_controls_json LONGTEXT NOT NULL,
    widget_constraints_json LONGTEXT NOT NULL,
    status VARCHAR(50) NOT NULL,
    revision INT UNSIGNED NOT NULL DEFAULT 1,
    metadata_json LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_quadrant_variants_slot_key (slot_key),
    UNIQUE KEY uq_quadrant_variants_quadrant_version (quadrant_id, story_version_id),
    UNIQUE KEY uq_quadrant_variants_position (position),
    CONSTRAINT fk_quadrant_variants_quadrant FOREIGN KEY (quadrant_id) REFERENCES quadrants (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_quadrant_variants_story_version FOREIGN KEY (story_version_id) REFERENCES story_versions (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE media_assets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quadrant_variant_id BIGINT UNSIGNED NOT NULL,
    asset_path VARCHAR(500) NULL,
    expected_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    aspect_ratio VARCHAR(50) NULL,
    alt_text VARCHAR(500) NOT NULL,
    caption TEXT NULL,
    status VARCHAR(50) NOT NULL,
    checksum CHAR(64) NULL,
    revision INT UNSIGNED NOT NULL DEFAULT 1,
    metadata_json LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_media_assets_quadrant_variant_id (quadrant_variant_id),
    KEY idx_media_assets_expected_path (expected_path),
    CONSTRAINT fk_media_assets_quadrant_variant FOREIGN KEY (quadrant_variant_id) REFERENCES quadrant_variants (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
