CREATE TABLE story_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    session_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    dominant_version_id BIGINT UNSIGNED NULL,
    schema_version VARCHAR(50) NOT NULL,
    mechanism_version VARCHAR(50) NOT NULL,
    rules_version VARCHAR(50) NOT NULL,
    resolution_mode VARCHAR(50) NOT NULL,
    input_state_json LONGTEXT NOT NULL,
    resolved_state_json LONGTEXT NOT NULL,
    continuity_payload_json LONGTEXT NOT NULL,
    resolution_trace_json LONGTEXT NOT NULL,
    seed BIGINT UNSIGNED NOT NULL,
    revision INT UNSIGNED NOT NULL DEFAULT 1,
    idempotency_key VARCHAR(191) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_story_runs_public_id (public_id),
    UNIQUE KEY uq_story_runs_idempotency_key (idempotency_key),
    KEY idx_story_runs_session_id (session_id),
    KEY idx_story_runs_user_id (user_id),
    KEY idx_story_runs_dominant_version_id (dominant_version_id),
    CONSTRAINT fk_story_runs_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_story_runs_dominant_version FOREIGN KEY (dominant_version_id) REFERENCES story_versions (id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE story_run_panels (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    story_run_id BIGINT UNSIGNED NOT NULL,
    quadrant_id BIGINT UNSIGNED NOT NULL,
    quadrant_variant_id BIGINT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL,
    selection_reason VARCHAR(100) NOT NULL,
    panel_payload_json LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_story_run_panels_run_quadrant (story_run_id, quadrant_id),
    UNIQUE KEY uq_story_run_panels_run_position (story_run_id, position),
    KEY idx_story_run_panels_quadrant_id (quadrant_id),
    KEY idx_story_run_panels_quadrant_variant_id (quadrant_variant_id),
    CONSTRAINT fk_story_run_panels_run FOREIGN KEY (story_run_id) REFERENCES story_runs (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_story_run_panels_quadrant FOREIGN KEY (quadrant_id) REFERENCES quadrants (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_story_run_panels_quadrant_variant FOREIGN KEY (quadrant_variant_id) REFERENCES quadrant_variants (id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
