<?php
declare(strict_types=1);
$root=dirname(__DIR__); $errors=[];
function fail(string $m): void { global $errors; $errors[]=$m; }
function readJson(string $p): array { try { $v=json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR); return is_array($v)?$v:[]; } catch(Throwable $e){ fail(basename($p).': '.$e->getMessage()); return []; } }
function sequence(array $items,string $field,int $count,string $label): void { $v=array_column($items,$field); sort($v); if($v!==range(1,$count)) fail("{$label}: posições não contínuas"); }
function unique(array $items,string $field,string $label): void { $v=array_column($items,$field); if(count($v)!==count(array_unique($v))) fail("{$label}: {$field} duplicado"); }
$files=['controls'=>'story-controls.json','widgets'=>'story-widgets.json','versions'=>'story-versions.json','quadrants'=>'quadrants.json','slots'=>'quadrant-slots.json']; $d=[];
foreach($files as $k=>$f){$d[$k]=readJson("$root/data/$f"); if(($d[$k]['schemaVersion']??null)!=='1.0.0'||($d[$k]['locale']??null)!=='pt-BR')fail("$f: cabeçalho inválido");}
foreach(glob("$root/contracts/*.json") as $p){$s=readJson($p); foreach(['$schema','$id','title','description','type','required','properties','additionalProperties'] as $k)if(!array_key_exists($k,$s))fail(basename($p).": campo $k ausente"); if(($s['$schema']??'')!=='https://json-schema.org/draft/2020-12/schema')fail(basename($p).': draft incorreto');}
$c=$d['controls']['items']??[];$w=$d['widgets']['items']??[];$v=$d['versions']['items']??[];$q=$d['quadrants']['items']??[];$s=$d['slots']['items']??[];
foreach([['controls',$c,32],['widgets',$w,4],['versions',$v,7],['quadrants',$q,29],['slots',$s,203]] as [$n,$a,$count]){if(count($a)!==$count)fail("$n: esperado $count");unique($a,'id',$n);sequence($a,$n==='versions'?'position':'position',$count,$n);}
$cids=array_column($c,'id');$wids=array_column($w,'id');$vids=array_column($v,'id');$qids=array_column($q,'id');
$families=array_count_values(array_column($c,'familyId'));if(count($families)!==4||array_unique(array_values($families))!==[8])fail('controles: famílias devem conter 8 itens');
foreach($c as $x){if(($x['controlType']??'')!=='switch'||($x['defaultValue']??true)!==false||($x['enabled']??false)!==true)fail("controle {$x['id']}: defaults inválidos");foreach(array_merge($x['conflicts'],$x['synergies']) as $r)if(!in_array($r,$cids,true))fail("controle {$x['id']}: referência $r");}
foreach($w as $x){unique($x['parameters'],'id',"widget {$x['id']}");foreach($x['parameters'] as $p){if(in_array($p['type'],['range','number'],true)&&($p['min']>$p['max']||$p['defaultValue']<$p['min']||$p['defaultValue']>$p['max']))fail("parâmetro {$p['id']}: limites");if($p['type']==='select'&&!in_array($p['defaultValue'],$p['options'],true))fail("parâmetro {$p['id']}: opção padrão");}}
unique($w,'panelId','widgets');unique($w,'activationButtonId','widgets');unique($v,'title','versions');
$paramMap=[];foreach($w as $x)$paramMap[$x['id']]=array_column($x['parameters'],'id');
foreach($v as $x){$sum=$x['temporalProfile']['past']+$x['temporalProfile']['present']+$x['temporalProfile']['future'];if(abs($sum-1)>0.001)fail("versão {$x['id']}: perfil temporal soma $sum");foreach(array_merge($x['requiredTags'],$x['preferredTags'],$x['excludedTags']) as $t)if(!in_array($t,$cids,true))fail("versão {$x['id']}: controle $t inexistente");foreach($x['defaultWidgetConfiguration'] as $wid=>$cfg){if(!isset($paramMap[$wid]))fail("versão {$x['id']}: widget $wid");foreach(array_keys($cfg) as $pid)if(!in_array($pid,$paramMap[$wid]??[],true))fail("versão {$x['id']}: parâmetro $pid");}}
foreach($q as $i=>$x){$n=$i+1;$id=sprintf('q%02d',$n);if($x['id']!==$id||$x['number']!==$n||$x['stableKey']!==$id)fail("quadrante $id: identidade");if($x['previousQuadrant']!==($n===1?null:sprintf('q%02d',$n-1))||$x['nextQuadrant']!==($n===29?null:sprintf('q%02d',$n+1)))fail("quadrante $id: continuidade");if($x['gutterBefore']!==sprintf('g%02d',$n-1)||$x['gutterAfter']!==sprintf('g%02d',$n))fail("quadrante $id: sarjetas");foreach($x['affectedByControls'] as $r)if(!in_array($r,$cids,true))fail("quadrante $id: controle $r");foreach($x['affectedByWidgets'] as $r)if(!in_array($r,$wids,true))fail("quadrante $id: widget $r");if($x['allowedVersionIds']!==$vids)fail("quadrante $id: versões");}
$perQ=$perV=[];$comb=[];foreach($s as $x){$expected=$x['quadrantId'].'-'.$x['versionId'];$pos=(($x['quadrantNumber']-1)*7)+$x['versionNumber'];$path="/assets/story/quadrants/{$x['quadrantId']}/{$x['versionId']}/{$expected}.png";if($x['id']!==$expected||$x['slotId']!==$expected||$x['position']!==$pos||$x['asset']['expectedPath']!==$path)fail("slot {$x['id']}: identidade/posição/caminho");if(!in_array($x['quadrantId'],$qids,true)||!in_array($x['versionId'],$vids,true))fail("slot {$x['id']}: referência");if($x['status']==='empty'&&$x['asset']['path']!==null)fail("slot {$x['id']}: empty com asset");$perQ[$x['quadrantId']]=($perQ[$x['quadrantId']]??0)+1;$perV[$x['versionId']]=($perV[$x['versionId']]??0)+1;$comb[]=$expected;}
if(count(array_unique($comb))!==203||array_unique(array_values($perQ))!==[7]||array_unique(array_values($perV))!==[29])fail('slots: cardinalidade por quadrante/versão');
if($errors){foreach($errors as $e)fwrite(STDERR,"[ERRO] $e\n");fwrite(STDERR,'[ERRO] '.count($errors)." erro(s).\n");exit(1);}foreach([['story-controls.json',32,'controles'],['story-widgets.json',4,'Widgets'],['story-versions.json',7,'versões'],['quadrants.json',29,'quadrantes'],['quadrant-slots.json',203,'slots']] as [$f,$n,$l])echo "[OK] $f: $n $l válidos\n";echo "[OK] Referências cruzadas válidas\n[OK] Contratos narrativos aprovados\n";
