<?php
declare(strict_types=1);
namespace Tna\Database;
use PDO; use RuntimeException; use Tna\Validation\ManifestValidator;
final class SeederRunner
{
    public function __construct(private readonly PDO $pdo, private readonly string $root, private ?array $manifests=null){}
    public function check(): array { $this->manifests(); return $this->counts(); }
    public function apply(): array { $this->manifests(); $this->pdo->beginTransaction(); try{ $files=glob($this->root.'/database/seeds/*.php')?:[]; sort($files); foreach($files as $seed){$fn=require $seed; if(!is_callable($fn)){throw new RuntimeException("Seed $seed must return callable.");} $fn($this->pdo,$this->manifests,$this);} $this->pdo->commit(); }catch(\Throwable $e){ if($this->pdo->inTransaction()){$this->pdo->rollBack();} throw $e;} return $this->counts(); }
    public function verify(): array { $m=$this->manifests(); $checks=[]; foreach(['schema_migrations','story_controls','story_widgets','story_versions','quadrants','quadrant_variants','media_assets','public_snapshots'] as $t){$checks["table:$t"]=$this->tableExists($t);} foreach(glob($this->root.'/database/migrations/*.sql')?:[] as $f){$checks['migration:'.basename($f,'.sql')]=$this->migrationApplied(basename($f,'.sql'));} foreach(['story-controls','story-widgets','story-versions','quadrants','quadrant-slots'] as $n){$checks["json:$n"]=json_encode($m[$n],JSON_THROW_ON_ERROR)!==false;} $counts=$this->counts(); foreach(['controls'=>32,'widgets'=>4,'versions'=>7,'quadrants'=>29,'variants'=>203,'assets'=>203] as $k=>$v){$checks["count:$k"]=($counts[$k]??-1)===$v;} $checks['first_slot:q01-v01']=$this->scalar('SELECT slot_key FROM quadrant_variants ORDER BY position LIMIT 1')==='q01-v01'; $checks['last_slot:q29-v07']=$this->scalar('SELECT slot_key FROM quadrant_variants ORDER BY position DESC LIMIT 1')==='q29-v07'; $checks['seven_slots_per_quadrant']=(int)$this->scalar('SELECT COUNT(*) FROM (SELECT quadrant_id FROM quadrant_variants GROUP BY quadrant_id HAVING COUNT(*)<>7) x')===0; $checks['twenty_nine_slots_per_version']=(int)$this->scalar('SELECT COUNT(*) FROM (SELECT story_version_id FROM quadrant_variants GROUP BY story_version_id HAVING COUNT(*)<>29) x')===0; $checks['no_variant_orphans']=(int)$this->scalar('SELECT COUNT(*) FROM quadrant_variants v LEFT JOIN quadrants q ON q.id=v.quadrant_id LEFT JOIN story_versions sv ON sv.id=v.story_version_id WHERE q.id IS NULL OR sv.id IS NULL')===0; $checks['no_asset_orphans']=(int)$this->scalar('SELECT COUNT(*) FROM media_assets a LEFT JOIN quadrant_variants v ON v.id=a.quadrant_variant_id WHERE v.id IS NULL')===0; foreach(['story_controls:stable_key','story_widgets:stable_key','story_versions:stable_key','quadrants:stable_key','quadrant_variants:slot_key','media_assets:quadrant_variant_id'] as $spec){[$t,$c]=explode(':',$spec); $checks["no_duplicates:$t.$c"]=(int)$this->scalar("SELECT COUNT(*) FROM (SELECT $c FROM $t GROUP BY $c HAVING COUNT(*)>1) x")===0;} return ['ok'=>!in_array(false,$checks,true),'counts'=>$counts,'checks'=>$checks]; }
    private function manifests(): array { return $this->manifests ??= (new ManifestValidator())->loadAll($this->root); }
    public function counts(): array { return ['controls'=>(int)$this->scalar('SELECT COUNT(*) FROM story_controls'),'widgets'=>(int)$this->scalar('SELECT COUNT(*) FROM story_widgets'),'versions'=>(int)$this->scalar('SELECT COUNT(*) FROM story_versions'),'quadrants'=>(int)$this->scalar('SELECT COUNT(*) FROM quadrants'),'variants'=>(int)$this->scalar('SELECT COUNT(*) FROM quadrant_variants'),'assets'=>(int)$this->scalar('SELECT COUNT(*) FROM media_assets')]; }
    public function scalar(string $sql): mixed { return $this->pdo->query($sql)->fetchColumn(); }
    private function tableExists(string $t): bool { $s=$this->pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?'); $s->execute([$t]); return (int)$s->fetchColumn()===1; }
    private function migrationApplied(string $v): bool { $s=$this->pdo->prepare('SELECT COUNT(*) FROM schema_migrations WHERE version=?'); $s->execute([$v]); return (int)$s->fetchColumn()===1; }
}
