import { dashboardHubDemoData, IS_DEMO_DATA } from '../data/dashboard-hub-demo.js';

const STORAGE_KEY = 'dashboard-hub:v1:user-state';
const FEATURE_STORAGE_KEY = 'dashboard-hub:v2:feature-state';
const CURRENT_VERSION = 1;
const selectors = { root:'[data-dashboard-hub]', search:'[data-dashboard-search]', shortcutGrid:'[data-shortcut-grid]', widgetActivationBar:'[data-widget-activation-bar]', widgetSection:'[data-widget-section]', widgetGrid:'[data-widget-grid]', toggle:'[data-widget-toggle]', menu:'[data-widget-menu]', live:'[data-dashboard-live]' };
const dashboardState = { items: [], shortcuts:{}, features:{}, widgets:{}, activeShortcutId:null, activeWidgetId:null, expanded:true, widgetSectionExpanded:false, widgetStates:{}, dirtyWidgets:new Set(), renderedWidgets:new Set(), query:'', loading:false, error:null, userId:null, transitionInProgress:false, lastOpenedShortcutId:null, dashboardRevision:0, restoringExternalState:false };
const shortcutWidgetMap = {};
const specializedShortcutWidgets = {};
const widgetActivationItems = [
  { id:'comparison', title:'Comparação', widgetId:'comparison-widget', enabled:true, order:1, metadata:{} },
  { id:'states', title:'Estados', widgetId:'states-widget', enabled:true, order:2, metadata:{} },
  { id:'time', title:'Tempo', widgetId:'time-widget', enabled:true, order:3, metadata:{} },
  { id:'tasks', title:'Tarefas', widgetId:'tasks-widget', enabled:true, order:4, metadata:{} }
];

const dashboardRepository = { async loadDashboard(){ return loadDemoDashboard(); }, async saveFeatureToggleState(payload){ persistFeatureState(); return { success:true, data:payload, demo:IS_DEMO_DATA }; }, async saveWidgetState(payload){ persistLocalDemoState(payload); return { success:true, data:payload, demo:IS_DEMO_DATA }; } };
const clone = (v) => typeof structuredClone === 'function' ? structuredClone(v) : JSON.parse(JSON.stringify(v));
const normalize = (value) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/\s+/g, ' ');
const slug = (value) => normalize(value).replace(/\s+/g, '-');
const debounce = (fn, wait=150) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), wait); }; };
const prefersReducedMotion = () => window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const nextDashboardRevision = () => ++dashboardState.dashboardRevision;
const publicWidgetState = (widget) => Object.fromEntries((widget?.parameters||[]).map((p)=>[p.id,p.value ?? p.defaultValue ?? null]));
const publicWidgetsState = () => Object.fromEntries(Object.values(dashboardState.widgets).map((w)=>[w.id,publicWidgetState(w)]));
const publicControlsState = () => Object.fromEntries(Object.entries(dashboardState.features).map(([id,state])=>[id,Boolean(state.enabled)]));
const emit = (eventName, detail={}) => { if(dashboardState.restoringExternalState) return; const narrative = eventName==='dashboard:feature-toggle'||eventName==='dashboard:parameter-change'||eventName==='dashboard:widget-save'||eventName==='dashboard:widget-reset'; const dashboardRevision = detail.dashboardRevision ?? (narrative ? nextDashboardRevision() : dashboardState.dashboardRevision); window.dispatchEvent(new CustomEvent(eventName, { detail:{ schemaVersion:'1.0.0', source:'dashboard', ...detail, ...(narrative?{dashboardRevision}:{}), timestamp:Date.now() } })); };
const text = (value) => document.createTextNode(String(value ?? ''));
function el(tag, className, attrs={}) { const node=document.createElement(tag); if(className) node.className=className; Object.entries(attrs).forEach(([k,v])=>{ if(v===null||v===undefined||v===false) return; if(k==='text') node.textContent=v; else if(k==='dataset') Object.assign(node.dataset,v); else node.setAttribute(k, v===true?'':String(v)); }); return node; }
const initials = (title) => String(title || '?').split(/\s+/).slice(0,2).map((p)=>p[0]).join('').toUpperCase();

function defaultParameters(type='generic') { const base=[{ id:'visibility', type:'select', label:'Visibilidade', value:'public', defaultValue:'public', options:[{value:'public',label:'Pública'},{value:'private',label:'Privada'},{value:'team',label:'Equipe'}], required:true },{ id:'priority', type:'range', label:'Prioridade', value:55, defaultValue:50, min:0, max:100, step:5, unit:'%' },{ id:'notes', type:'textarea', label:'Notas', value:'', defaultValue:'', maxLength:240 }];
  if(type==='timer') return [{ id:'session-duration', type:'number', label:'Duração da sessão', description:'Tempo previsto em minutos.', value:30, defaultValue:30, min:5, max:180, step:5, unit:'min', required:true },{ id:'mode', type:'select', label:'Modo', value:'Foco', defaultValue:'Foco', options:['Foco','Intervalo','Livre'].map((x)=>({value:x,label:x})) },{ id:'auto-start', type:'checkbox', label:'Iniciar automaticamente', value:false, defaultValue:false }];
  if(type==='tasks') return [{ id:'task-title', type:'text', label:'Nova tarefa', value:'', defaultValue:'', maxLength:80 },{ id:'task-priority', type:'select', label:'Prioridade', value:'média', defaultValue:'média', options:['baixa','média','alta'].map((x)=>({value:x,label:x})) },{ id:'task-tags', type:'tags', label:'Tags', value:'revisão,dados', defaultValue:'' }];
  if(type==='comparison') return [{ id:'criteria', type:'text', label:'Critérios', value:'clareza, impacto', defaultValue:'clareza' },{ id:'weight', type:'range', label:'Peso dos critérios', value:60, defaultValue:50, min:0, max:100, step:10, unit:'%' },{ id:'period', type:'date', label:'Período de referência', value:'', defaultValue:'' }];
  return base;
}
function buildWidgetFromShortcut(shortcut, widgetId) { const typeMap={agenda:'calendar',notas:'editor',metricas:'metrics',tempo:'timer'}; return { id:widgetId, itemId:shortcut.id, type:typeMap[shortcut.id] || 'generic', title:shortcut.title, subtitle:'Painel configurável', description:`Configure este painel de ${shortcut.title.toLowerCase()} conforme os dados disponíveis.`, status:'ready', openMode:'focus', order:shortcut.order, enabled:true, visible:true, parameters:defaultParameters(typeMap[shortcut.id] || 'generic'), actions:[{id:'save',label:'Salvar alterações',type:'primary',enabled:true},{id:'reset',label:'Restaurar padrão',type:'secondary',enabled:true}], metadata:{ version:1, updatedAt:null, updatedBy:null, revision:0, syncStatus:'local' }, data:{} }; }
function normalizeWidget(widget, shortcut) { return { ...widget, itemId:shortcut?.id || widget.itemId, openMode:widget.openMode || 'focus', description:widget.description || widget.subtitle || 'Configure este painel. Os campos definitivos serão carregados conforme os dados disponíveis.', parameters:widget.parameters || defaultParameters(widget.type), actions:widget.actions || [{id:'save',label:'Salvar alterações',type:'primary',enabled:true},{id:'reset',label:'Restaurar padrão',type:'secondary',enabled:true}], metadata:{ version:1, revision:0, syncStatus:'local', ...(widget.metadata || {}) } }; }
function loadPersistedState(){ try { const raw=localStorage.getItem(STORAGE_KEY); if(!raw) return null; const parsed=JSON.parse(raw); return parsed.version===CURRENT_VERSION ? parsed.state : null; } catch(error){ console.warn('[Dashboard persistence]', error); return null; } }
function persistLocalDemoState(payload={}){ const parameters={}; Object.values(dashboardState.widgets).forEach((w)=>{ parameters[w.id]=(w.parameters||[]).map((p)=>({id:p.id,value:p.value,savedValue:p.savedValue ?? p.value})); }); localStorage.setItem(STORAGE_KEY, JSON.stringify({ version:CURRENT_VERSION, updatedAt:new Date().toISOString(), state:{ activeWidgetId:dashboardState.activeWidgetId, expanded:dashboardState.expanded, dirtyWidgets:[...dashboardState.dirtyWidgets], parameters, lastPayload:payload } })); }
function restoreFeatureState(){ try{ const raw=localStorage.getItem(FEATURE_STORAGE_KEY); if(!raw) return {}; const parsed=JSON.parse(raw); return parsed.version===2 && parsed.features ? parsed.features : {}; }catch(error){ console.warn('[Dashboard feature persistence]', error); return {}; } }
function persistFeatureState(){ const features={}; Object.entries(dashboardState.features).forEach(([id,state])=>{ features[id]=Boolean(state.enabled); }); localStorage.setItem(FEATURE_STORAGE_KEY, JSON.stringify({ version:2, updatedAt:new Date().toISOString(), features })); }
async function saveFeatureToggleState(payload){ return dashboardRepository.saveFeatureToggleState(payload); }
async function saveWidgetParameters(payload){ return dashboardRepository.saveWidgetState(payload); }
async function loadDemoDashboard(){ await new Promise((r)=>setTimeout(r,80)); const data=clone(dashboardHubDemoData); const widgetsById=Object.fromEntries((data.widgets||[]).map((w)=>[w.id,w])); const persisted=loadPersistedState(); const items=(data.shortcuts||[]).map((shortcut)=>{ const explicit = specializedShortcutWidgets[shortcut.id] || shortcutWidgetMap[shortcut.id] || `${shortcut.id}-widget`; const widget = normalizeWidget(widgetsById[explicit] || buildWidgetFromShortcut(shortcut, explicit), shortcut); if(persisted?.parameters?.[widget.id]) widget.parameters.forEach((p)=>{ const saved=persisted.parameters[widget.id].find((x)=>x.id===p.id); if(saved) p.value=saved.value; }); return { ...shortcut, enabled:false, available:true, disabledReason:null, visible:true, widget, permissions:[], parameters:{}, userState:{ enabled:false, lastChangedAt:null, isFavorite:shortcut.isFavorite, isPinned:shortcut.isPinned, interactionCount:shortcut.interactionCount || 0 }, metadata:{ permissions:[], tags:[], ...(shortcut.metadata || {}) } }; }); return { items, persisted, demoWidgets:data.widgets || [] }; }

function createShortcut(item){ const enabled=getFeatureState(item.id).enabled; const b=el('button','shortcut-item feature-toggle',{ type:'button',role:'switch','data-feature-toggle':true,'data-feature-id':item.id,'aria-checked':String(enabled),'aria-label':`${enabled?'Desativar':'Ativar'} ${item.title}` }); b.dataset.status=item.status||'active'; const frame=el('span','shortcut-item__icon-frame feature-toggle__icon-frame'); const ph=el('span','shortcut-item__icon-placeholder',{'aria-hidden':'true','data-icon-slot':true,text:initials(item.shortTitle||item.title)}); const img=el('img','shortcut-item__icon',{'data-shortcut-icon':true,alt:item.iconAlt||'',width:38,height:38}); img.hidden=true; frame.append(ph,img); const title=el('span','shortcut-item__title feature-toggle__title',{text:item.shortTitle||item.title}); const state=el('span','feature-toggle__state',{'aria-hidden':'true',text:enabled?'Ligado':'Desligado'}); const badge=el('span','shortcut-item__badge',{'data-shortcut-badge':true,text:item.badge}); badge.hidden=!item.badge; b.classList.toggle('is-enabled',enabled); b.append(frame,title,state,badge); return b; }
function baseWidget(widget){ return el('article','widget-card',{ id:widget.id,'data-widget-card':true,'data-widget-id':widget.id,'data-widget-type':widget.type,'aria-hidden':'true',hidden:true }); }
function widgetShell(widget){ const card=baseWidget(widget); const header=el('header','widget-card__header'); const titleWrap=el('div'); titleWrap.append(el('p','widget-card__eyebrow',{text:widget.type||'painel'})); const title=el('h3','widget-card__title',{text:widget.title||'Widget',tabindex:'-1'}); titleWrap.append(title, el('p','widget-card__description',{text:widget.description||'Configure este painel. Os campos definitivos serão carregados conforme os dados disponíveis.'})); header.append(titleWrap, renderActions(widget)); card.append(header, el('div','widget-card__status',{'aria-live':'polite',text:statusText(widget)})); return card; }
const statusText=(w)=> w.metadata?.syncStatus==='conflict' ? 'Há uma versão mais recente deste painel.' : `${w.status || 'ready'} · ${w.metadata?.syncStatus || 'local'}`;
function renderActions(widget){ const wrap=el('div','widget-card__actions'); (widget.actions||[]).forEach((a)=>wrap.append(el('button',`widget-button ${a.type==='primary'?'widget-button--primary':''}`,{type:'button','data-widget-action':a.id,disabled:a.enabled===false,text:a.label}))); wrap.append(el('button','widget-button widget-button--close',{type:'button','data-widget-action':'close',text:'Fechar painel'})); return wrap; }
function renderWidget(widget){ try { const renderer = widgetRenderers[widget.type] || renderGenericParameterWidget; return renderer(widget); } catch(error){ emit('dashboard:widget-error',{widgetId:widget.id, action:'render'}); console.error('[Dashboard widget]',{widgetId:widget.id, error}); return renderWidgetError(widget,error); } }
function renderComparisonWidget(widget){ const c=widgetShell(widget), body=el('div','widget-card__content comparison-body'); (widget.data?.participants||[]).slice(0,2).forEach((p,i)=>{ if(i) body.append(el('strong','',{text:'×'})); const part=el('div','participant'); part.append(el('span','participant-mark',{text:initials(p.name)}),el('strong','',{text:p.name}),el('small','widget-meta',{text:p.detail})); body.append(part); }); c.append(body, renderParametersForm(widget), renderFooter(widget)); return c; }
function renderListWidget(widget){ const c=widgetShell(widget), list=el('ul','widget-list widget-card__content'); (widget.data?.items||[]).forEach((it)=>{ const row=el('li','widget-row'); const left=el('span'); left.append(text(it.label), el('small','',{text:it.secondary||''})); row.append(left, el('strong','',{text:it.value||''})); list.append(row); }); c.append(list, renderParametersForm(widget), renderFooter(widget)); return c; }
function renderTimerWidget(widget){ const c=widgetShell(widget), face=el('div','timer-face widget-card__content'); face.style.setProperty('--progress', Number(widget.data?.progress||0)); face.append(el('span','',{text:widget.data?.remaining||'00:00'})); c.append(face, renderParametersForm(widget), renderFooter(widget)); return c; }
function renderTasksWidget(widget){ const c=widgetShell(widget), list=el('ul','task-list widget-card__content'); (widget.data?.items||[]).forEach((task)=>{ const row=el('li','task-item'); if(task.completed) row.classList.add('is-complete'); row.append(el('span','task-check',{'aria-hidden':'true'})); const body=el('span'); body.append(text(task.title), el('div','task-meta',{text:`${task.priority||'normal'} · ${task.assignee||'sem responsável'} · ${task.dueDate||'sem data'}`})); row.append(body); list.append(row); }); c.append(list, renderParametersForm(widget), renderFooter(widget)); return c; }
function renderGenericParameterWidget(widget){ const c=widgetShell(widget); c.append(el('div','widget-card__content',{text:'Configure este painel. Os campos definitivos serão carregados conforme os dados disponíveis.'}), renderParametersForm(widget), renderFooter(widget)); return c; }
function renderWidgetError(widget){ const c=widgetShell(widget); c.append(el('p','widget-meta',{text:'Não foi possível carregar este widget, mas os demais painéis continuam disponíveis.'})); return c; }
const widgetRenderers={ comparison:renderComparisonWidget, list:renderListWidget, timer:renderTimerWidget, tasks:renderTasksWidget };

function renderParametersForm(widget){ const form=el('form','widget-card__parameters',{'data-widget-parameters':true}); (widget.parameters||[]).filter((p)=>p.visible!==false).forEach((p)=>form.append(renderParameter(widget,p))); return form; }
function renderParameter(widget,p){ const r=parameterRenderers[p.type] || renderUnknownParameter; return r(widget,p); }
function fieldWrap(widget,p){ const id=`${widget.id}-${p.id}`; const wrap=el('label','parameter-field',{'data-parameter-id':p.id}); wrap.append(el('span','parameter-field__label',{text:p.label||p.id})); if(p.description) wrap.append(el('small','parameter-field__description',{text:p.description})); return {wrap,id}; }
function inputAttrs(widget,p,type){ return { id:`${widget.id}-${p.id}`, name:p.id, type, value:p.value ?? '', min:p.min, max:p.max, step:p.step, required:p.required, disabled:p.disabled, 'data-parameter-input':true, 'data-parameter-id':p.id, 'aria-describedby':`${widget.id}-${p.id}-meta` }; }
function renderTextParameter(w,p){ const {wrap}=fieldWrap(w,p); wrap.append(el('input','parameter-input',inputAttrs(w,p,'text')), meta(w,p)); return wrap; }
function renderTextareaParameter(w,p){ const {wrap}=fieldWrap(w,p); const ta=el('textarea','parameter-input',inputAttrs(w,p,'text')); ta.value=p.value||''; wrap.append(ta, meta(w,p)); return wrap; }
function renderNumberParameter(w,p){ const {wrap}=fieldWrap(w,p); const group=el('span','parameter-stepper'); group.append(el('button','parameter-stepper__button',{type:'button','data-parameter-step':'down','data-parameter-id':p.id,text:'−'}), el('input','parameter-input',inputAttrs(w,p,'number')), el('button','parameter-stepper__button',{type:'button','data-parameter-step':'up','data-parameter-id':p.id,text:'+'})); wrap.append(group, meta(w,p)); return wrap; }
function renderRangeParameter(w,p){ const {wrap}=fieldWrap(w,p); wrap.append(el('input','parameter-input',inputAttrs(w,p,'range')), meta(w,p)); return wrap; }
function renderSelectParameter(w,p){ const {wrap}=fieldWrap(w,p); const select=el('select','parameter-input',{...inputAttrs(w,p,'text'), type:null}); (p.options||[]).forEach((o)=>{ const opt=el('option','',{value:o.value,text:o.label}); if(String(o.value)===String(p.value)) opt.selected=true; select.append(opt); }); wrap.append(select, meta(w,p)); return wrap; }
function renderMultiSelectParameter(w,p){ const node=renderSelectParameter(w,{...p}); node.querySelector('select')?.setAttribute('multiple',''); return node; }
function renderCheckboxParameter(w,p){ const {wrap}=fieldWrap(w,p); const input=el('input','parameter-checkbox',{...inputAttrs(w,p,'checkbox'), value:'true'}); input.checked=Boolean(p.value); wrap.append(input, meta(w,p)); return wrap; }
function renderDateParameter(w,p){ const {wrap}=fieldWrap(w,p); wrap.append(el('input','parameter-input',inputAttrs(w,p,'date')), meta(w,p)); return wrap; }
function renderTimeParameter(w,p){ const {wrap}=fieldWrap(w,p); wrap.append(el('input','parameter-input',inputAttrs(w,p,'time')), meta(w,p)); return wrap; }
function renderDurationParameter(w,p){ return renderNumberParameter(w,{...p, unit:p.unit||'min'}); }
function renderTagsParameter(w,p){ return renderTextParameter(w,{...p, description:p.description||'Separe tags por vírgula.'}); }
function renderUnknownParameter(w,p){ console.warn('[Dashboard parameter] tipo desconhecido', p.type, p); return renderTextParameter(w,{...p, label:p.label||`Campo ${p.id}`, value:String(p.value??'')}); }
const parameterRenderers={ text:renderTextParameter, textarea:renderTextareaParameter, number:renderNumberParameter, range:renderRangeParameter, select:renderSelectParameter, multiselect:renderMultiSelectParameter, checkbox:renderCheckboxParameter, date:renderDateParameter, time:renderTimeParameter, duration:renderDurationParameter, tags:renderTagsParameter };
function meta(w,p){ const dirty=p.isDirty?' · alterações não salvas':''; return el('small','parameter-field__meta',{ id:`${w.id}-${p.id}-meta`, text:`Atual: ${p.value ?? 'vazio'}${p.unit?' '+p.unit:''} · padrão: ${p.defaultValue ?? 'vazio'}${dirty}` }); }
function renderFooter(widget){ const foot=el('footer','widget-card__footer'); foot.append(el('span','widget-meta',{text:`rev. ${widget.metadata?.revision ?? 0} · ${widget.metadata?.syncStatus || 'local'}`}), el('span','widget-dirty',{text:'Alterações não salvas', hidden:!dashboardState.dirtyWidgets.has(widget.id)})); return foot; }

function initializeState(items,persisted,demoWidgets=[]){ const persistedFeatures=restoreFeatureState(); dashboardState.items=items; dashboardState.shortcuts={}; dashboardState.features={}; dashboardState.widgets={}; dashboardState.activeShortcutId=null; dashboardState.activeWidgetId=null; dashboardState.widgetSectionExpanded=false; dashboardState.expanded=false; dashboardState.transitionInProgress=false; items.forEach((item)=>{ const enabled=Boolean(persistedFeatures[item.id] ?? item.userState?.enabled ?? item.enabled); item.enabled=enabled; item.userState={...(item.userState||{}), enabled}; dashboardState.shortcuts[item.id]=item; dashboardState.features[item.id]={ enabled, available:item.available!==false, metadata:item.metadata||{}, userState:item.userState||{} }; }); widgetActivationItems.forEach((activation)=>{ const explicit=demoWidgets.find((widget)=>widget.id===activation.widgetId); const source=items.find((item)=>item.widget.id===activation.widgetId) || items.find((item)=>item.widget.title===activation.title); const model=explicit || source?.widget; if(model) dashboardState.widgets[activation.widgetId]=normalizeWidget({...model, id:activation.widgetId, title:activation.title, order:activation.order}, source); }); if(persisted){ dashboardState.dirtyWidgets=new Set(persisted.dirtyWidgets||[]); } }
function renderDashboardState(root){ const q=normalize(dashboardState.query); const shortcuts=dashboardState.items.filter((i)=>!q || normalize([i.title,i.description,i.widget.title,i.widget.type,...(i.metadata?.tags||[])].join(' ')).includes(q)).sort((a,b)=>a.order-b.order); const grid=root.querySelector(selectors.shortcutGrid); grid.replaceChildren(...shortcuts.map(createShortcut)); const wg=root.querySelector(selectors.widgetGrid); if(!dashboardState.renderedWidgets.size){ const frag=document.createDocumentFragment(); widgetActivationItems.sort((a,b)=>a.order-b.order).forEach((i)=>{ const model=dashboardState.widgets[i.widgetId]; if(!model) return; const card=renderWidget(model); setWidgetVisibility(card,false); frag.append(card); dashboardState.renderedWidgets.add(model.id); }); wg.replaceChildren(frag); } updateVisualState(root); }
function getFeatureButtonById(root, featureId){ return root.querySelector(`[data-feature-toggle][data-feature-id="${CSS.escape(featureId)}"]`); }
function getWidgetButtonById(root, widgetId){ return root.querySelector(`[data-widget-activation][data-widget-target="${CSS.escape(widgetId)}"]`); }
function getWidgetById(root, widgetId){ return root.querySelector(`[data-widget-card][data-widget-id="${CSS.escape(widgetId)}"]`); }
function setWidgetVisibility(widget,isVisible){ if(!widget) return; widget.hidden=!isVisible; widget.setAttribute('aria-hidden',String(!isVisible)); widget.classList.toggle('is-active',isVisible); widget.toggleAttribute('data-active',isVisible); if('inert' in widget) widget.inert=!isVisible; widget.querySelectorAll('a,button,input,select,textarea,[tabindex]').forEach((node)=>{ if(!isVisible){ if(!node.hasAttribute('data-prev-tabindex')) node.setAttribute('data-prev-tabindex', node.getAttribute('tabindex') ?? ''); node.setAttribute('tabindex','-1'); } else if(node.hasAttribute('data-prev-tabindex')){ const previous=node.getAttribute('data-prev-tabindex'); if(previous) node.setAttribute('tabindex',previous); else node.removeAttribute('tabindex'); node.removeAttribute('data-prev-tabindex'); } }); }
function getFeatureState(featureId){ return dashboardState.features[featureId] || { enabled:false }; }
function renderFeatureState(featureId, root=document){ const button=getFeatureButtonById(root,featureId); if(!button) return; const item=dashboardState.shortcuts[featureId]; const enabled=Boolean(getFeatureState(featureId).enabled); button.classList.toggle('is-enabled',enabled); button.setAttribute('aria-checked',String(enabled)); button.setAttribute('aria-label',`${enabled?'Desativar':'Ativar'} ${item?.title || featureId}`); const state=button.querySelector('.feature-toggle__state'); if(state) state.textContent=enabled?'Ligado':'Desligado'; }
function setFeatureEnabled(featureId, enabled, root=document){ if(!dashboardState.features[featureId]) dashboardState.features[featureId]={enabled:false}; dashboardState.features[featureId].enabled=Boolean(enabled); dashboardState.features[featureId].userState={...(dashboardState.features[featureId].userState||{}), enabled:Boolean(enabled), lastChangedAt:new Date().toISOString()}; if(dashboardState.shortcuts[featureId]) dashboardState.shortcuts[featureId].userState={...(dashboardState.shortcuts[featureId].userState||{}), enabled:Boolean(enabled), lastChangedAt:dashboardState.features[featureId].userState.lastChangedAt}; renderFeatureState(featureId,root); persistFeatureState(); saveFeatureToggleState({ featureId, enabled:Boolean(enabled), userId:dashboardState.userId, metadata:dashboardState.features[featureId].metadata||{} }); emit('dashboard:feature-toggle',{ featureId, enabled:Boolean(enabled) }); }
function toggleFeature(featureId, root=document){ const current=Boolean(getFeatureState(featureId).enabled); setFeatureEnabled(featureId,!current,root); announce(root,`${dashboardState.shortcuts[featureId]?.title || featureId} ${!current?'ativada':'desativada'}.`); }
function hideAllWidgets(root,{exceptWidgetId=null}={}){ root.querySelectorAll('[data-widget-card]').forEach((widget)=>{ if(exceptWidgetId && widget.dataset.widgetId===exceptWidgetId) return; setWidgetVisibility(widget,false); }); }
function updateWidgetGridState(root){ const grid=root.querySelector(selectors.widgetGrid); const hasActive=Boolean(dashboardState.activeWidgetId && dashboardState.expanded); grid?.setAttribute('data-has-active-widget',String(hasActive)); if(grid) grid.style.maxHeight=hasActive ? `${grid.scrollHeight + 80}px` : '0px'; }
function setWidgetButtonActive(button,isActive){ if(!button) return; button.classList.toggle('is-active',isActive); button.setAttribute('aria-pressed',String(isActive)); }
function deactivateAllWidgetButtons(root){ root.querySelectorAll('[data-widget-activation]').forEach((button)=>setWidgetButtonActive(button,false)); }
function updateVisualState(root){ root.querySelectorAll('[data-feature-toggle]').forEach((button)=>renderFeatureState(button.dataset.featureId,root)); deactivateAllWidgetButtons(root); const activeButton=dashboardState.activeWidgetId && getWidgetButtonById(root,dashboardState.activeWidgetId); if(activeButton) setWidgetButtonActive(activeButton,true); hideAllWidgets(root,{exceptWidgetId:dashboardState.expanded ? dashboardState.activeWidgetId : null}); const activeWidget=dashboardState.expanded && dashboardState.activeWidgetId && getWidgetById(root,dashboardState.activeWidgetId); if(activeWidget) setWidgetVisibility(activeWidget,true); root.querySelectorAll('[data-widget-card]').forEach((card)=>{ card.querySelector('.widget-dirty')?.toggleAttribute('hidden', !dashboardState.dirtyWidgets.has(card.dataset.widgetId)); }); const section=root.querySelector(selectors.widgetSection); section?.classList.toggle('is-collapsed',!dashboardState.expanded); const toggle=root.querySelector(selectors.toggle); toggle?.setAttribute('aria-expanded',String(dashboardState.expanded)); toggle?.setAttribute('aria-label',dashboardState.expanded?'Recolher widget ativo':'Expandir widget ativo'); const active=dashboardState.widgets[dashboardState.activeWidgetId]; let meta=section?.querySelector('[data-widget-active-meta]'); if(!meta){ meta=el('p','widget-section__active-meta',{'data-widget-active-meta':true}); section?.querySelector('.widget-section__title-group')?.append(meta); } meta.textContent=active ? `${active.title}${dashboardState.dirtyWidgets.has(active.id)?' · alterações não salvas':''}` : 'Selecione um painel para começar.'; updateWidgetGridState(root); }
function ensureWidgetRendered(root, widgetId){ let widget=getWidgetById(root,widgetId); if(widget) return widget; const model=dashboardState.widgets[widgetId]; try{ dashboardState.widgets[widgetId]=model; widget=renderWidget(model); setWidgetVisibility(widget,false); root.querySelector(selectors.widgetGrid)?.append(widget); dashboardState.renderedWidgets.add(widgetId); return widget; } catch(error){ return renderLocalWidgetError(root,{widgetId,error}); } }
function renderLocalWidgetError(root,{widgetId,error}){ console.error('[Dashboard widget association]',{widgetId,action:'open',error,timestamp:new Date().toISOString()}); const model={ id:widgetId, itemId:null, type:'erro', title:widgetActivationItems.find((item)=>item.widgetId===widgetId)?.title || 'Widget', description:'Não foi possível carregar este painel.', status:'error', actions:[], metadata:{revision:0,syncStatus:'error'}, parameters:[] }; dashboardState.widgets[widgetId]=model; const card=renderWidgetError(model); card.append(el('button','widget-button',{type:'button','data-widget-action':'retry',text:'Tentar novamente'}), renderFooter(model)); setWidgetVisibility(card,false); root.querySelector(selectors.widgetGrid)?.append(card); return card; }
async function animateWidget(widget,show){ if(!widget || prefersReducedMotion() || !widget.animate) { setWidgetVisibility(widget,show); return; } if(show) setWidgetVisibility(widget,true); const animation=widget.animate([{opacity:show?0:1,transform:`translateY(${show?'8px':'0'})`},{opacity:show?1:0,transform:`translateY(${show?'0':'-6px'})`}],{duration:show?180:120,easing:'ease',fill:'forwards'}); await animation.finished.catch(()=>{}); if(!show) setWidgetVisibility(widget,false); }
async function activateWidgetFromButton(button,{focus=true,scroll=true}={}){ if(!button || dashboardState.transitionInProgress) return; const widgetId=button.dataset.widgetTarget; if(!widgetId){ emit('dashboard:widget-error',{reason:'missing-target'}); return; } if(dashboardState.activeWidgetId===widgetId && dashboardState.expanded) return; dashboardState.transitionInProgress=true; try{ const root=button.closest(selectors.root) || document.querySelector(selectors.root); const previousWidget=getWidgetById(root, dashboardState.activeWidgetId || ''); if(previousWidget && previousWidget.dataset.widgetId!==widgetId) await animateWidget(previousWidget,false); hideAllWidgets(root); deactivateAllWidgetButtons(root); let widget=ensureWidgetRendered(root,widgetId); if(!widget){ widget=renderLocalWidgetError(root,{widgetId,error:new Error('missing-widget')}); } setWidgetButtonActive(button,true); dashboardState.activeShortcutId=null; dashboardState.activeWidgetId=widgetId; dashboardState.expanded=true; dashboardState.widgetSectionExpanded=true; await animateWidget(widget,true); updateVisualState(root); persistLocalDemoState(); if(scroll) scrollToActiveWidget(widget); if(focus) focusActiveWidget(widget); const title=dashboardState.widgets[widgetId]?.title || button.textContent.trim(); announce(root,`Painel ${title} aberto.`); emit('dashboard:widget-activate',{widgetId}); } finally { dashboardState.transitionInProgress=false; } }
function closeActiveWidget(root, returnFocus=true){ const widgetId=dashboardState.activeWidgetId; const button=widgetId && getWidgetButtonById(root,widgetId); hideAllWidgets(root); deactivateAllWidgetButtons(root); dashboardState.activeShortcutId=null; dashboardState.activeWidgetId=null; dashboardState.widgetSectionExpanded=false; dashboardState.expanded=false; updateVisualState(root); persistLocalDemoState(); const title=dashboardState.widgets[widgetId]?.title || 'Widget'; announce(root,`Painel ${title} fechado.`); emit('dashboard:widget-close',{widgetId}); if(returnFocus) button?.focus({preventScroll:true}); }
function scrollToActiveWidget(widget){ if(!widget) return; const rect=widget.getBoundingClientRect(); if(rect.top>=0 && rect.bottom<=window.innerHeight) return; const header=document.querySelector('[data-site-header]') || document.querySelector('header'); const top=rect.top + window.scrollY - (header?.getBoundingClientRect().height || 0) - 20; window.scrollTo({ top:Math.max(0,top), behavior:prefersReducedMotion()?'auto':'smooth' }); }
function focusActiveWidget(widget){ widget?.querySelector('.widget-card__title')?.focus({preventScroll:true}); }
function updateWidgetParameter(widgetId, parameterId, value, root){ const w=dashboardState.widgets[widgetId], p=w?.parameters?.find((x)=>x.id===parameterId); if(!p) return; p.value=value; p.isDirty=String(value)!==String(p.savedValue ?? p.defaultValue ?? ''); p.isValid=validateParameter(p); dashboardState.dirtyWidgets.add(widgetId); emit('dashboard:parameter-change',{widgetId, parameterId, value, widgetState:publicWidgetState(w)}); updateVisualState(root); persistLocalDemoState(); }
function validateParameter(p){ if(p.required && (p.value===''||p.value===null||p.value===undefined)) { p.validationMessage='Campo obrigatório.'; return false; } const n=Number(p.value); if(['number','range','duration'].includes(p.type) && (Number.isNaN(n) || (p.min!==undefined && n<p.min) || (p.max!==undefined && n>p.max))) { p.validationMessage='Valor fora dos limites.'; return false; } p.validationMessage=null; return true; }
async function saveWidget(widgetId, root){ const w=dashboardState.widgets[widgetId]; if(!w) return; const valid=(w.parameters||[]).every(validateParameter); if(!valid){ announce(root,'Revise os campos indicados antes de salvar.'); return; } w.metadata.syncStatus='syncing'; updateVisualState(root); try{ await saveWidgetParameters({ widgetId, itemId:w.itemId, userId:dashboardState.userId, parameters:w.parameters, metadata:w.metadata }); (w.parameters||[]).forEach((p)=>{ p.savedValue=p.value; p.isDirty=false; }); dashboardState.dirtyWidgets.delete(widgetId); w.metadata.syncStatus='synced'; w.metadata.updatedAt=new Date().toISOString(); w.metadata.revision=(w.metadata.revision||0)+1; emit('dashboard:widget-save',{widgetId,itemId:w.itemId,parameters:publicWidgetState(w)}); announce(root,`Alterações do painel ${w.title} salvas.`); }catch(error){ w.metadata.syncStatus='error'; emit('dashboard:widget-error',{widgetId,action:'save'}); announce(root,'Não foi possível salvar as alterações.'); } updateVisualState(root); persistLocalDemoState(); }
function resetWidget(widgetId, root){ const w=dashboardState.widgets[widgetId]; (w?.parameters||[]).forEach((p)=>{ p.value=p.defaultValue; p.isDirty=false; }); dashboardState.dirtyWidgets.delete(widgetId); emit('dashboard:widget-reset',{widgetId,parameters:publicWidgetState(w)}); rerenderWidget(root, widgetId); updateVisualState(root); }
function rerenderWidget(root, widgetId){ const old=root.querySelector(`[data-widget-id="${CSS.escape(widgetId)}"]`); if(old) old.replaceWith(renderWidget(dashboardState.widgets[widgetId])); }
function announce(root,msg){ const live=root.querySelector(selectors.live); if(live){ live.hidden=false; live.textContent=msg; } }
function scrollToWidgetSection(section){ if(!section) return; const rect=section.getBoundingClientRect(); if(rect.top>=0 && rect.bottom <= window.innerHeight) return; const header=document.querySelector('[data-site-header]') || document.querySelector('header'); const top=rect.top + window.scrollY - (header?.getBoundingClientRect().height || 0) - 20; window.scrollTo({ top:Math.max(0,top), behavior:prefersReducedMotion()?'auto':'smooth' }); }

async function initDashboardHub(){ const root=document.querySelector(selectors.root); if(!root) return; dashboardState.loading=true; root.setAttribute('aria-busy','true'); try{ const {items,persisted,demoWidgets}=await dashboardRepository.loadDashboard(); initializeState(items,persisted,demoWidgets); renderDashboardState(root); root.setAttribute('aria-busy','false'); hideAllWidgets(root); updateVisualState(root); }catch(error){ console.error('[Dashboard hub]',error); announce(root,'Não foi possível carregar esta área.'); }
 const input=root.querySelector(`${selectors.search} input`); const onSearch=debounce(()=>{ dashboardState.query=input.value; renderDashboardState(root); emit('dashboard:search',{query:dashboardState.query}); },150); input?.addEventListener('input',onSearch); root.querySelector(selectors.search)?.addEventListener('submit',(e)=>{ e.preventDefault(); const first=root.querySelector('[data-feature-toggle]:not([aria-disabled="true"])'); if(first) toggleFeature(first.dataset.featureId, root); });
 root.addEventListener('click',(e)=>{ const feature=e.target.closest('[data-feature-toggle]'); if(feature){ e.preventDefault(); toggleFeature(feature.dataset.featureId, root); return; } const activation=e.target.closest('[data-widget-activation]'); if(activation){ e.preventDefault(); activateWidgetFromButton(activation); return; } const step=e.target.closest('[data-parameter-step]'); if(step){ const card=step.closest('[data-widget-card]'), p=dashboardState.widgets[card.dataset.widgetId].parameters.find((x)=>x.id===step.dataset.parameterId); const next=Number(p.value||0)+(step.dataset.parameterStep==='up'?Number(p.step||1):-Number(p.step||1)); updateWidgetParameter(card.dataset.widgetId,p.id,Math.min(Number(p.max??next),Math.max(Number(p.min??next),next)),root); rerenderWidget(root,card.dataset.widgetId); updateVisualState(root); return; } const action=e.target.closest('[data-widget-action]'); if(action){ const card=action.closest('[data-widget-card]'); if(action.dataset.widgetAction==='save') saveWidget(card.dataset.widgetId,root); else if(action.dataset.widgetAction==='reset') resetWidget(card.dataset.widgetId,root); else if(action.dataset.widgetAction==='close') closeActiveWidget(root); else if(action.dataset.widgetAction==='retry') activateWidgetFromButton(getWidgetButtonById(root,card.dataset.widgetId)); else emit('dashboard:widget-action',{widgetId:card?.dataset.widgetId,action:action.dataset.widgetAction}); } });
 root.addEventListener('input',(e)=>{ const input=e.target.closest('[data-parameter-input]'); if(!input) return; const card=input.closest('[data-widget-card]'); updateWidgetParameter(card.dataset.widgetId,input.dataset.parameterId,input.type==='checkbox'?input.checked:input.value,root); });
 const toggle=root.querySelector(selectors.toggle); toggle?.addEventListener('click',()=>{ dashboardState.expanded=toggle.getAttribute('aria-expanded')!=='true'; if(dashboardState.expanded && dashboardState.activeWidgetId){ activateWidgetFromButton(getWidgetButtonById(root,dashboardState.activeWidgetId), {focus:false, scroll:false}); } else { updateVisualState(root); persistLocalDemoState(); } }); setupMenu(root); }
function setupMenu(root){ const button=root.querySelector(selectors.menu); if(!button) return; button.setAttribute('aria-haspopup','menu'); button.setAttribute('aria-expanded','false'); let menu; const close=()=>{ menu?.remove(); menu=null; button.setAttribute('aria-expanded','false'); button.focus(); }; button.addEventListener('click',()=>{ if(menu){ close(); return; } menu=el('div','widget-menu-popover',{role:'menu'}); ['Ver todos os atalhos','Escolher outro painel','Mostrar somente fixados','Restaurar ordem','Recolher painel ativo','Restaurar configurações','Gerenciar painéis'].forEach((label,i)=>menu.append(el('button','widget-menu-popover__item',{type:'button',role:'menuitem','data-menu-action':slug(label),text:label,tabindex:i?'-1':'0'}))); button.after(menu); button.setAttribute('aria-expanded','true'); menu.querySelector('button')?.focus(); }); root.addEventListener('keydown',(e)=>{ if(e.key==='Escape' && menu) close(); }); root.addEventListener('click',(e)=>{ const item=e.target.closest('[data-menu-action]'); if(!item) return; if(item.dataset.menuAction==='ver-todos-os-atalhos' || item.dataset.menuAction==='escolher-outro-painel'){ root.querySelector(selectors.shortcutGrid)?.scrollIntoView({behavior:prefersReducedMotion()?'auto':'smooth',block:'start'}); } if(item.dataset.menuAction==='recolher-painel-ativo'){ dashboardState.expanded=false; updateVisualState(root); } emit('dashboard:widget-action',{action:item.dataset.menuAction}); close(); }); }

function applyExternalState(state,{emitEvents=false}={}){ const root=document.querySelector(selectors.root); dashboardState.restoringExternalState=!emitEvents; try{ Object.entries(state?.controls||{}).forEach(([id,enabled])=>{ if(dashboardState.features[id]){ dashboardState.features[id].enabled=Boolean(enabled); renderFeatureState(id,root||document); } }); Object.entries(state?.widgets||{}).forEach(([widgetId,params])=>{ const w=dashboardState.widgets[widgetId]; if(!w||!params||typeof params!=='object') return; (w.parameters||[]).forEach((p)=>{ if(Object.prototype.hasOwnProperty.call(params,p.id)){ p.value=params[p.id]; p.savedValue=params[p.id]; p.isDirty=false; } }); if(root) rerenderWidget(root,widgetId); }); if(root) updateVisualState(root); persistFeatureState(); persistLocalDemoState(); } finally { dashboardState.restoringExternalState=false; } }
function getStateSnapshot(){ return { schemaVersion:'1.0.0', source:'dashboard', controls:publicControlsState(), widgets:publicWidgetsState(), dashboardRevision:dashboardState.dashboardRevision, timestamp:Date.now() }; }
window.TNADashboardHub={getStateSnapshot,applyExternalState,isReady:()=>Boolean(dashboardState.items.length)};
document.addEventListener('DOMContentLoaded', initDashboardHub);
