const MANIFEST_URLS = {
  index: '/data/story-manifest-index.json',
  versions: '/data/story-versions.json',
  quadrants: '/data/quadrants.json',
  slots: '/data/quadrant-slots.json'
};
const ID_RE = { quadrant: /^q\d{2}$/, version: /^v\d{2}$/ };
let controller = null;
let initialized = false;
const state = { ready:false, loading:false, defaultVersionId:'v01', activeVersionId:'v01', quadrants:[], versions:[], slots:[], quadrantMap:new Map(), versionMap:new Map(), slotMap:new Map(), selections:new Map(), host:null, grid:null, status:null, live:null };

function logStoryGridError(error, context={}) { console.error('[TNAStoryGrid]', { ...context, message:error?.message||String(error), timestamp:Date.now() }); }
function emit(name, detail) { window.dispatchEvent(new CustomEvent(name, { detail })); }
async function fetchJson(resource, url, signal) { const res = await fetch(url, { signal, headers:{ Accept:'application/json' } }); if (!res.ok) { const e = new Error(`Falha ao carregar ${resource}: HTTP ${res.status}`); e.status=res.status; e.url=url; e.resource=resource; throw e; } return res.json(); }
function getItems(manifest, name) { if (!manifest || !Array.isArray(manifest.items)) throw new Error(`${name} não contém items[]`); return manifest.items; }
function validateUnique(items, label) { const seen=new Set(); for (const item of items) { if (!item?.id || seen.has(item.id)) throw new Error(`ID duplicado ou ausente em ${label}: ${item?.id}`); seen.add(item.id); } }
function validateManifestData(index, versions, quadrants, slots, defaultVersionId) {
  const expected = index?.manifests || {};
  if (versions.length !== expected.versions?.count || quadrants.length !== expected.quadrants?.count || slots.length !== expected.slots?.count) throw new Error('Cardinalidade dos manifestos divergente do índice.');
  validateUnique(versions,'versions'); validateUnique(quadrants,'quadrants'); validateUnique(slots,'slots');
  versions.forEach((v,i)=>{ const id=`v${String(i+1).padStart(2,'0')}`; if(v.id!==id || v.versionNumber!==i+1) throw new Error(`Versão inválida: ${v.id}`); });
  quadrants.forEach((q,i)=>{ const id=`q${String(i+1).padStart(2,'0')}`; if(q.id!==id || q.number!==i+1) throw new Error(`Quadrante inválido: ${q.id}`); });
  const versionIds = new Set(versions.map(v=>v.id)); const quadrantIds = new Set(quadrants.map(q=>q.id)); const byQuadrant = new Map();
  slots.forEach(slot=>{ if(!quadrantIds.has(slot.quadrantId) || !versionIds.has(slot.versionId)) throw new Error(`Slot com referência inválida: ${slot.id}`); const key=`${slot.quadrantId}:${slot.versionId}`; byQuadrant.set(slot.quadrantId, (byQuadrant.get(slot.quadrantId)||0)+1); if (slot.id !== `${slot.quadrantId}-${slot.versionId}`) throw new Error(`Slot com ID divergente: ${slot.id}`); });
  quadrants.forEach(q=>{ if (byQuadrant.get(q.id)!==versions.length) throw new Error(`${q.id} não possui ${versions.length} slots.`); if (!slots.some(s=>s.quadrantId===q.id && s.versionId===defaultVersionId)) throw new Error(`${q.id} não possui slot padrão.`); });
}
function summarizeFixedFunction(text='') { const clean=String(text).replace(/\s+/g,' ').trim(); if (clean.length <= 82) return clean; const sentence = clean.split(/(?<=[.!?])\s+/)[0]; return sentence.length <= 96 ? sentence : clean.slice(0, 82).replace(/\s+\S*$/,''); }
function validateAssetPath(path) { if (path === null || path === undefined) return null; if (typeof path !== 'string' || !path.trim()) return null; if (/^(javascript|data):/i.test(path) || path.includes('..')) return null; if (/^https:\/\//i.test(path) || path.startsWith('/assets/') || path.startsWith('assets/')) return path; return null; }
function renderPanelMedia(slot) { const media=document.createElement('div'); media.className='story-panel__media'; const path=validateAssetPath(slot?.asset?.path); if (path) { const img=document.createElement('img'); img.src=path; img.alt=slot.altText || `Quadrante ${String(slot.quadrantNumber).padStart(2,'0')}, versão ${String(slot.versionNumber).padStart(2,'0')}`; img.width=slot.dimensions?.width || 1200; img.height=slot.dimensions?.height || 900; img.loading='lazy'; img.decoding='async'; media.append(img); return media; }
  const ph=document.createElement('div'); ph.className='story-panel__placeholder'; ph.setAttribute('aria-label', slot.altText || `${slot.quadrantId} ${slot.versionId}`); const mark=document.createElement('span'); mark.className='story-panel__placeholder-mark'; [['story-panel__placeholder-number', slot.quadrantId.toUpperCase()], ['story-panel__placeholder-version', slot.versionId.toUpperCase()], ['story-panel__placeholder-slot', slot.id]].forEach(([c,t])=>{ const s=document.createElement('span'); s.className=c; s.textContent=t; mark.append(s); }); ph.append(mark); media.append(ph); return media; }
function buildPanel(q, slot) { const fig=document.createElement('figure'); fig.className=`story-panel story-panel--${q.id}`; fig.setAttribute('role','listitem'); fig.dataset.storyPanel=''; updatePanelDataset(fig,q,slot); fig.setAttribute('aria-labelledby',`story-panel-title-${q.id}`); fig.append(renderPanelMedia(slot)); const cap=document.createElement('figcaption'); cap.className='story-panel__caption'; const num=document.createElement('span'); num.className='story-panel__number'; num.textContent=String(q.number).padStart(2,'0'); const fn=document.createElement('span'); fn.id=`story-panel-title-${q.id}`; fn.className='story-panel__function'; const summary=summarizeFixedFunction(q.fixedFunction); fn.textContent=summary; fn.title=q.fixedFunction; fig.setAttribute('aria-label',`Quadrante ${q.number}, versão ${slot.versionNumber}: ${q.fixedFunction}`); const code=document.createElement('span'); code.className='story-panel__slot-code'; code.textContent=`Q${String(q.number).padStart(2,'0')} · V${String(slot.versionNumber).padStart(2,'0')}`; cap.append(num,fn,code); fig.append(cap); return fig; }
function updatePanelDataset(fig,q,slot){ fig.dataset.quadrantId=q.id; fig.dataset.quadrantNumber=String(q.number); fig.dataset.versionId=slot.versionId; fig.dataset.slotId=slot.id; fig.dataset.blockId=q.blockId; fig.dataset.aspectClass=q.aspectClass; if(q.gutterBefore) fig.dataset.gutterBefore=q.gutterBefore; if(q.gutterAfter) fig.dataset.gutterAfter=q.gutterAfter; }
function applyPanelVersion(qid, vid) { const q=state.quadrantMap.get(qid), v=state.versionMap.get(vid); if(!ID_RE.quadrant.test(qid)) return {success:false,error:{code:'INVALID_QUADRANT_ID'}}; if(!ID_RE.version.test(vid)) return {success:false,error:{code:'INVALID_VERSION_ID'}}; if(!q) return {success:false,error:{code:'QUADRANT_NOT_FOUND'}}; if(!v) return {success:false,error:{code:'VERSION_NOT_FOUND'}}; const slot=state.slotMap.get(`${qid}:${vid}`); if(!slot) return {success:false,error:{code:'SLOT_NOT_FOUND'}}; const fig=state.grid?.querySelector(`[data-story-panel][data-quadrant-id="${qid}"]`); if(!fig) return {success:false,error:{code:'PANEL_NOT_FOUND'}}; fig.classList.add('is-updating'); updatePanelDataset(fig,q,slot); const old=fig.querySelector('.story-panel__media'); old.replaceWith(renderPanelMedia(slot)); fig.querySelector('.story-panel__slot-code').textContent=`Q${String(q.number).padStart(2,'0')} · V${String(slot.versionNumber).padStart(2,'0')}`; fig.setAttribute('aria-label',`Quadrante ${q.number}, versão ${slot.versionNumber}: ${q.fixedFunction}`); state.selections.set(qid,vid); setTimeout(()=>fig.classList.remove('is-updating'), 190); state.live.textContent=`Quadrante ${q.number} atualizado para a versão ${String(slot.versionNumber).padStart(2,'0')}.`; emit('tna:story-panel-changed',{quadrantId:qid,versionId:vid,slotId:slot.id,timestamp:Date.now()}); return {success:true, quadrantId:qid, versionId:vid, slotId:slot.id}; }
async function init({reload=false}={}) { if (initialized && !reload) return; initialized=true; state.host=document.querySelector('[data-story-grid-host]'); if(!state.host) return; state.grid=state.host.querySelector('[data-story-grid]'); state.status=state.host.querySelector('[data-story-grid-status]'); state.live=state.host.querySelector('[data-story-grid-live]'); state.defaultVersionId=state.host.dataset.defaultVersion || 'v01'; state.loading=true; state.ready=false; state.host.removeAttribute('data-story-grid-ready'); state.status.hidden=false; state.status.textContent='Preparando os 29 quadrantes…'; state.grid.replaceChildren(); controller?.abort(); controller=new AbortController(); try { const [indexM, versionM, quadrantM, slotM] = await Promise.all([fetchJson('index',MANIFEST_URLS.index,controller.signal),fetchJson('versions',MANIFEST_URLS.versions,controller.signal),fetchJson('quadrants',MANIFEST_URLS.quadrants,controller.signal),fetchJson('slots',MANIFEST_URLS.slots,controller.signal)]); const versions=getItems(versionM,'versions'), quadrants=getItems(quadrantM,'quadrants'), slots=getItems(slotM,'slots'); validateManifestData(indexM, versions, quadrants, slots, state.defaultVersionId); Object.assign(state,{versions,quadrants,slots,quadrantMap:new Map(quadrants.map(q=>[q.id,q])),versionMap:new Map(versions.map(v=>[v.id,v])),slotMap:new Map(slots.map(s=>[`${s.quadrantId}:${s.versionId}`,s])),selections:new Map()}); const frag=document.createDocumentFragment(); quadrants.forEach(q=>{ const slot=state.slotMap.get(`${q.id}:${state.defaultVersionId}`); state.selections.set(q.id,state.defaultVersionId); frag.append(buildPanel(q,slot)); }); state.grid.append(frag); state.status.hidden=true; state.ready=true; state.loading=false; state.host.dataset.storyGridReady='true'; emit('tna:story-grid-ready',{quadrants:quadrants.length,versions:versions.length,slots:slots.length,activeVersionId:state.defaultVersionId,timestamp:Date.now()}); } catch(error) { state.loading=false; state.ready=false; logStoryGridError(error,{stage:'init',resource:error.resource,url:error.url,status:error.status}); state.status.replaceChildren(); const wrap=document.createElement('span'); wrap.className='story-grid-error__message'; wrap.textContent='Não foi possível preparar a estrutura narrativa.'; const retry=document.createElement('button'); retry.type='button'; retry.className='story-grid-error__retry'; retry.textContent='Tentar novamente'; retry.addEventListener('click',()=>init({reload:true}),{once:true}); state.status.className='story-grid-error'; state.status.append(wrap,retry); state.status.hidden=false; emit('tna:story-grid-error',{message:error.message,stage:'init',timestamp:Date.now()}); } }
window.TNAStoryGrid = { getState(){ return {ready:state.ready, loading:state.loading, quadrants:state.quadrants.length, versions:state.versions.length, slots:state.slots.length, defaultVersionId:state.defaultVersionId, selections:this.getActiveSelections()}; }, getActiveSelections(){ return Array.from(state.selections, ([quadrantId,versionId])=>({quadrantId,versionId,slotId:`${quadrantId}-${versionId}`})); }, setQuadrantVersion:applyPanelVersion, setAllQuadrantsVersion(versionId){ const out=state.quadrants.map(q=>applyPanelVersion(q.id,versionId)); return {success:out.every(r=>r.success), results:out}; }, applySelections(selections){ if(!Array.isArray(selections)) return {success:false,error:{code:'INVALID_SELECTIONS'}}; const out=selections.map(s=>applyPanelVersion(s.quadrantId,s.versionId)); return {success:out.every(r=>r.success), results:out}; }, resetToDefault(){ return this.setAllQuadrantsVersion(state.defaultVersionId); }, reload(){ initialized=false; return init({reload:true}); } };
document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded',()=>init(),{once:true}) : init();
